// Complete data for all 118 elements of the periodic table
export interface Element {
  atomicNumber: number
  symbol: string
  name: string
  atomicMass: number
  category: string
  electronConfig: string
  electronegativity: number | null
  density: number | null
  meltingPoint: number | null
  boilingPoint: number | null
  discoveredBy: string
  yearDiscovered: number | string
  description: string
  shells: number[]
  color: string
  state: "solid" | "liquid" | "gas" | "unknown"
}

export const categoryColors: Record<string, string> = {
  "alkali-metal": "#ff6b6b",
  "alkaline-earth": "#ffa94d",
  "transition-metal": "#ffd43b",
  "post-transition": "#69db7c",
  metalloid: "#38d9a9",
  nonmetal: "#4dabf7",
  halogen: "#748ffc",
  "noble-gas": "#da77f2",
  lanthanide: "#f783ac",
  actinide: "#e599f7",
  unknown: "#868e96",
}

export const categoryNames: Record<string, string> = {
  "alkali-metal": "Alkali Metal",
  "alkaline-earth": "Alkaline Earth Metal",
  "transition-metal": "Transition Metal",
  "post-transition": "Post-Transition Metal",
  metalloid: "Metalloid",
  nonmetal: "Reactive Nonmetal",
  halogen: "Halogen",
  "noble-gas": "Noble Gas",
  lanthanide: "Lanthanide",
  actinide: "Actinide",
  unknown: "Unknown Properties",
}

export const elements: Element[] = [
  // Period 1
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.008,
    category: "nonmetal",
    electronConfig: "1s¹",
    electronegativity: 2.2,
    density: 0.00008988,
    meltingPoint: -259.16,
    boilingPoint: -252.87,
    discoveredBy: "Henry Cavendish",
    yearDiscovered: 1766,
    description: "Lightest element, most abundant in the universe. Used in fuel cells and rocket propellant.",
    shells: [1],
    color: "#ffffff",
    state: "gas",
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: 4.0026,
    category: "noble-gas",
    electronConfig: "1s²",
    electronegativity: null,
    density: 0.0001785,
    meltingPoint: -272.2,
    boilingPoint: -268.93,
    discoveredBy: "Pierre Janssen",
    yearDiscovered: 1868,
    description: "Second lightest element, used in balloons and cryogenics. Inert and non-toxic.",
    shells: [2],
    color: "#d9ffff",
    state: "gas",
  },

  // Period 2
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.94,
    category: "alkali-metal",
    electronConfig: "[He] 2s¹",
    electronegativity: 0.98,
    density: 0.534,
    meltingPoint: 180.54,
    boilingPoint: 1342,
    discoveredBy: "Johan August Arfwedson",
    yearDiscovered: 1817,
    description: "Lightest metal, used in batteries, aerospace, and psychiatric medication.",
    shells: [2, 1],
    color: "#cc80ff",
    state: "solid",
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: 9.0122,
    category: "alkaline-earth",
    electronConfig: "[He] 2s²",
    electronegativity: 1.57,
    density: 1.85,
    meltingPoint: 1287,
    boilingPoint: 2469,
    discoveredBy: "Louis Nicolas Vauquelin",
    yearDiscovered: 1798,
    description: "Lightweight, stiff metal used in aerospace, X-ray windows, and nuclear reactors.",
    shells: [2, 2],
    color: "#c2ff00",
    state: "solid",
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: 10.81,
    category: "metalloid",
    electronConfig: "[He] 2s² 2p¹",
    electronegativity: 2.04,
    density: 2.34,
    meltingPoint: 2076,
    boilingPoint: 3927,
    discoveredBy: "Joseph Louis Gay-Lussac",
    yearDiscovered: 1808,
    description: "Metalloid used in fiberglass, ceramics, and as a semiconductor dopant.",
    shells: [2, 3],
    color: "#ffb5b5",
    state: "solid",
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p²",
    electronegativity: 2.55,
    density: 2.267,
    meltingPoint: 3550,
    boilingPoint: 4027,
    discoveredBy: "Ancient",
    yearDiscovered: "Ancient",
    description: "Basis of all organic life. Found as diamond, graphite, and fullerenes.",
    shells: [2, 4],
    color: "#909090",
    state: "solid",
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p³",
    electronegativity: 3.04,
    density: 0.0012506,
    meltingPoint: -210.1,
    boilingPoint: -195.79,
    discoveredBy: "Daniel Rutherford",
    yearDiscovered: 1772,
    description: "Makes up 78% of Earth's atmosphere. Essential for life and used in fertilizers.",
    shells: [2, 5],
    color: "#3050f8",
    state: "gas",
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p⁴",
    electronegativity: 3.44,
    density: 0.001429,
    meltingPoint: -218.79,
    boilingPoint: -182.95,
    discoveredBy: "Carl Wilhelm Scheele",
    yearDiscovered: 1774,
    description: "Essential for respiration. Makes up 21% of atmosphere and 46% of Earth's crust.",
    shells: [2, 6],
    color: "#ff0d0d",
    state: "gas",
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998,
    category: "halogen",
    electronConfig: "[He] 2s² 2p⁵",
    electronegativity: 3.98,
    density: 0.001696,
    meltingPoint: -219.67,
    boilingPoint: -188.12,
    discoveredBy: "André-Marie Ampère",
    yearDiscovered: 1886,
    description: "Most electronegative element. Used in toothpaste, Teflon, and refrigerants.",
    shells: [2, 7],
    color: "#90e050",
    state: "gas",
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: 20.18,
    category: "noble-gas",
    electronConfig: "[He] 2s² 2p⁶",
    electronegativity: null,
    density: 0.0008999,
    meltingPoint: -248.59,
    boilingPoint: -246.08,
    discoveredBy: "William Ramsay",
    yearDiscovered: 1898,
    description: "Inert gas that glows red-orange in discharge tubes. Used in neon signs.",
    shells: [2, 8],
    color: "#b3e3f5",
    state: "gas",
  },

  // Period 3
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.99,
    category: "alkali-metal",
    electronConfig: "[Ne] 3s¹",
    electronegativity: 0.93,
    density: 0.971,
    meltingPoint: 97.72,
    boilingPoint: 883,
    discoveredBy: "Humphry Davy",
    yearDiscovered: 1807,
    description: "Soft, reactive metal. Essential nutrient. Used in street lights and as a coolant.",
    shells: [2, 8, 1],
    color: "#ab5cf2",
    state: "solid",
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "alkaline-earth",
    electronConfig: "[Ne] 3s²",
    electronegativity: 1.31,
    density: 1.738,
    meltingPoint: 650,
    boilingPoint: 1090,
    discoveredBy: "Joseph Black",
    yearDiscovered: 1755,
    description: "Lightweight structural metal. Essential for chlorophyll. Burns with bright white light.",
    shells: [2, 8, 2],
    color: "#8aff00",
    state: "solid",
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    atomicMass: 26.982,
    category: "post-transition",
    electronConfig: "[Ne] 3s² 3p¹",
    electronegativity: 1.61,
    density: 2.698,
    meltingPoint: 660.32,
    boilingPoint: 2519,
    discoveredBy: "Hans Christian Ørsted",
    yearDiscovered: 1825,
    description: "Most abundant metal in Earth's crust. Used in aircraft, packaging, and construction.",
    shells: [2, 8, 3],
    color: "#bfa6a6",
    state: "solid",
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.086,
    category: "metalloid",
    electronConfig: "[Ne] 3s² 3p²",
    electronegativity: 1.9,
    density: 2.3296,
    meltingPoint: 1414,
    boilingPoint: 3265,
    discoveredBy: "Jöns Jacob Berzelius",
    yearDiscovered: 1824,
    description: "Second most abundant element in Earth's crust. Basis of computer chips.",
    shells: [2, 8, 4],
    color: "#f0c8a0",
    state: "solid",
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: 30.974,
    category: "nonmetal",
    electronConfig: "[Ne] 3s² 3p³",
    electronegativity: 2.19,
    density: 1.82,
    meltingPoint: 44.15,
    boilingPoint: 280.5,
    discoveredBy: "Hennig Brand",
    yearDiscovered: 1669,
    description: "Essential for life (DNA, ATP). White phosphorus glows in the dark.",
    shells: [2, 8, 5],
    color: "#ff8000",
    state: "solid",
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: 32.06,
    category: "nonmetal",
    electronConfig: "[Ne] 3s² 3p⁴",
    electronegativity: 2.58,
    density: 2.067,
    meltingPoint: 115.21,
    boilingPoint: 444.6,
    discoveredBy: "Ancient",
    yearDiscovered: "Ancient",
    description: "Yellow element essential for proteins. Used in fertilizers and vulcanization.",
    shells: [2, 8, 6],
    color: "#ffff30",
    state: "solid",
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "halogen",
    electronConfig: "[Ne] 3s² 3p⁵",
    electronegativity: 3.16,
    density: 0.003214,
    meltingPoint: -101.5,
    boilingPoint: -34.04,
    discoveredBy: "Carl Wilhelm Scheele",
    yearDiscovered: 1774,
    description: "Yellow-green gas with strong odor. Used in water purification and PVC production.",
    shells: [2, 8, 7],
    color: "#1ff01f",
    state: "gas",
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: 39.948,
    category: "noble-gas",
    electronConfig: "[Ne] 3s² 3p⁶",
    electronegativity: null,
    density: 0.0017837,
    meltingPoint: -189.35,
    boilingPoint: -185.85,
    discoveredBy: "Lord Rayleigh",
    yearDiscovered: 1894,
    description: "Third most abundant gas in atmosphere. Used in welding and incandescent bulbs.",
    shells: [2, 8, 8],
    color: "#80d1e3",
    state: "gas",
  },

  // Period 4
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.098,
    category: "alkali-metal",
    electronConfig: "[Ar] 4s¹",
    electronegativity: 0.82,
    density: 0.862,
    meltingPoint: 63.38,
    boilingPoint: 759,
    discoveredBy: "Humphry Davy",
    yearDiscovered: 1807,
    description: "Essential nutrient for nerves and muscles. Reacts violently with water.",
    shells: [2, 8, 8, 1],
    color: "#8f40d4",
    state: "solid",
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "alkaline-earth",
    electronConfig: "[Ar] 4s²",
    electronegativity: 1.0,
    density: 1.54,
    meltingPoint: 842,
    boilingPoint: 1484,
    discoveredBy: "Humphry Davy",
    yearDiscovered: 1808,
    description: "Fifth most abundant element. Essential for bones, teeth, and cellular signaling.",
    shells: [2, 8, 8, 2],
    color: "#3dff00",
    state: "solid",
  },
  {
    atomicNumber: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicMass: 44.956,
    category: "transition-metal",
    electronConfig: "[Ar] 3d¹ 4s²",
    electronegativity: 1.36,
    density: 2.989,
    meltingPoint: 1541,
    boilingPoint: 2836,
    discoveredBy: "Lars Fredrik Nilson",
    yearDiscovered: 1879,
    description: "Lightweight transition metal used in aerospace alloys and sports equipment.",
    shells: [2, 8, 9, 2],
    color: "#e6e6e6",
    state: "solid",
  },
  {
    atomicNumber: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicMass: 47.867,
    category: "transition-metal",
    electronConfig: "[Ar] 3d² 4s²",
    electronegativity: 1.54,
    density: 4.54,
    meltingPoint: 1668,
    boilingPoint: 3287,
    discoveredBy: "William Gregor",
    yearDiscovered: 1791,
    description: "Strong, lightweight, corrosion-resistant. Used in aircraft, implants, and jewelry.",
    shells: [2, 8, 10, 2],
    color: "#bfc2c7",
    state: "solid",
  },
  {
    atomicNumber: 23,
    symbol: "V",
    name: "Vanadium",
    atomicMass: 50.942,
    category: "transition-metal",
    electronConfig: "[Ar] 3d³ 4s²",
    electronegativity: 1.63,
    density: 6.11,
    meltingPoint: 1910,
    boilingPoint: 3407,
    discoveredBy: "Andrés Manuel del Río",
    yearDiscovered: 1801,
    description: "Hard, silvery metal used in steel alloys and aerospace applications.",
    shells: [2, 8, 11, 2],
    color: "#a6a6ab",
    state: "solid",
  },
  {
    atomicNumber: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicMass: 51.996,
    category: "transition-metal",
    electronConfig: "[Ar] 3d⁵ 4s¹",
    electronegativity: 1.66,
    density: 7.15,
    meltingPoint: 1907,
    boilingPoint: 2671,
    discoveredBy: "Louis Nicolas Vauquelin",
    yearDiscovered: 1797,
    description: "Hard, lustrous metal. Used in stainless steel, chrome plating, and pigments.",
    shells: [2, 8, 13, 1],
    color: "#8a99c7",
    state: "solid",
  },
  {
    atomicNumber: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicMass: 54.938,
    category: "transition-metal",
    electronConfig: "[Ar] 3d⁵ 4s²",
    electronegativity: 1.55,
    density: 7.44,
    meltingPoint: 1246,
    boilingPoint: 2061,
    discoveredBy: "Johan Gottlieb Gahn",
    yearDiscovered: 1774,
    description: "Essential trace element. Used in steel production and batteries.",
    shells: [2, 8, 13, 2],
    color: "#9c7ac7",
    state: "solid",
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: 55.845,
    category: "transition-metal",
    electronConfig: "[Ar] 3d⁶ 4s²",
    electronegativity: 1.83,
    density: 7.874,
    meltingPoint: 1538,
    boilingPoint: 2861,
    discoveredBy: "Ancient",
    yearDiscovered: "Ancient",
    description: "Most used metal. Essential for hemoglobin. Core of Earth is mostly iron.",
    shells: [2, 8, 14, 2],
    color: "#e06633",
    state: "solid",
  },
  {
    atomicNumber: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicMass: 58.933,
    category: "transition-metal",
    electronConfig: "[Ar] 3d⁷ 4s²",
    electronegativity: 1.88,
    density: 8.86,
    meltingPoint: 1495,
    boilingPoint: 2927,
    discoveredBy: "Georg Brandt",
    yearDiscovered: 1735,
    description: "Used in blue pigments, magnets, and lithium-ion batteries.",
    shells: [2, 8, 15, 2],
    color: "#f090a0",
    state: "solid",
  },
  {
    atomicNumber: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicMass: 58.693,
    category: "transition-metal",
    electronConfig: "[Ar] 3d⁸ 4s²",
    electronegativity: 1.91,
    density: 8.912,
    meltingPoint: 1455,
    boilingPoint: 2913,
    discoveredBy: "Axel Fredrik Cronstedt",
    yearDiscovered: 1751,
    description: "Corrosion-resistant metal used in coins, stainless steel, and batteries.",
    shells: [2, 8, 16, 2],
    color: "#50d050",
    state: "solid",
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: 63.546,
    category: "transition-metal",
    electronConfig: "[Ar] 3d¹⁰ 4s¹",
    electronegativity: 1.9,
    density: 8.96,
    meltingPoint: 1084.62,
    boilingPoint: 2562,
    discoveredBy: "Ancient",
    yearDiscovered: "Ancient",
    description: "Excellent electrical conductor. Used in wiring, plumbing, and electronics.",
    shells: [2, 8, 18, 1],
    color: "#c88033",
    state: "solid",
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: 65.38,
    category: "transition-metal",
    electronConfig: "[Ar] 3d¹⁰ 4s²",
    electronegativity: 1.65,
    density: 7.134,
    meltingPoint: 419.53,
    boilingPoint: 907,
    discoveredBy: "India",
    yearDiscovered: "Ancient",
    description: "Essential trace element. Used in galvanizing steel and in batteries.",
    shells: [2, 8, 18, 2],
    color: "#7d80b0",
    state: "solid",
  },
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: 69.723,
    category: "post-transition",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p¹",
    electronegativity: 1.81,
    density: 5.907,
    meltingPoint: 29.76,
    boilingPoint: 2204,
    discoveredBy: "Paul Emile Lecoq de Boisbaudran",
    yearDiscovered: 1875,
    description: "Melts in your hand. Used in semiconductors, LEDs, and solar panels.",
    shells: [2, 8, 18, 3],
    color: "#c28f8f",
    state: "solid",
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: 72.63,
    category: "metalloid",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p²",
    electronegativity: 2.01,
    density: 5.323,
    meltingPoint: 938.25,
    boilingPoint: 2833,
    discoveredBy: "Clemens Winkler",
    yearDiscovered: 1886,
    description: "Semiconductor used in fiber optics, infrared optics, and electronics.",
    shells: [2, 8, 18, 4],
    color: "#668f8f",
    state: "solid",
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: 74.922,
    category: "metalloid",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p³",
    electronegativity: 2.18,
    density: 5.776,
    meltingPoint: 817,
    boilingPoint: 614,
    discoveredBy: "Albertus Magnus",
    yearDiscovered: 1250,
    description: "Toxic metalloid historically used in pigments and pesticides. Used in semiconductors.",
    shells: [2, 8, 18, 5],
    color: "#bd80e3",
    state: "solid",
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: 78.971,
    category: "nonmetal",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁴",
    electronegativity: 2.55,
    density: 4.809,
    meltingPoint: 221,
    boilingPoint: 685,
    discoveredBy: "Jöns Jacob Berzelius",
    yearDiscovered: 1817,
    description: "Essential trace element. Used in electronics, glass, and photocopiers.",
    shells: [2, 8, 18, 6],
    color: "#ffa100",
    state: "solid",
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: 79.904,
    category: "halogen",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁵",
    electronegativity: 2.96,
    density: 3.122,
    meltingPoint: -7.2,
    boilingPoint: 58.8,
    discoveredBy: "Antoine Jérôme Balard",
    yearDiscovered: 1826,
    description: "Only non-metallic liquid element at room temperature. Used in flame retardants.",
    shells: [2, 8, 18, 7],
    color: "#a62929",
    state: "liquid",
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicMass: 83.798,
    category: "noble-gas",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁶",
    electronegativity: 3.0,
    density: 0.003733,
    meltingPoint: -157.36,
    boilingPoint: -153.22,
    discoveredBy: "William Ramsay",
    yearDiscovered: 1898,
    description: "Noble gas used in high-performance light bulbs and lasers.",
    shells: [2, 8, 18, 8],
    color: "#5cb8d1",
    state: "gas",
  },

  // Period 5
  {
    atomicNumber: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicMass: 85.468,
    category: "alkali-metal",
    electronConfig: "[Kr] 5s¹",
    electronegativity: 0.82,
    density: 1.532,
    meltingPoint: 39.31,
    boilingPoint: 688,
    discoveredBy: "Robert Bunsen",
    yearDiscovered: 1861,
    description: "Soft, highly reactive alkali metal. Used in atomic clocks and medical imaging.",
    shells: [2, 8, 18, 8, 1],
    color: "#702eb0",
    state: "solid",
  },
  {
    atomicNumber: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicMass: 87.62,
    category: "alkaline-earth",
    electronConfig: "[Kr] 5s²",
    electronegativity: 0.95,
    density: 2.64,
    meltingPoint: 777,
    boilingPoint: 1382,
    discoveredBy: "William Cruickshank",
    yearDiscovered: 1790,
    description: "Produces brilliant red flames. Used in fireworks and glow-in-the-dark paints.",
    shells: [2, 8, 18, 8, 2],
    color: "#00ff00",
    state: "solid",
  },
  {
    atomicNumber: 39,
    symbol: "Y",
    name: "Yttrium",
    atomicMass: 88.906,
    category: "transition-metal",
    electronConfig: "[Kr] 4d¹ 5s²",
    electronegativity: 1.22,
    density: 4.469,
    meltingPoint: 1526,
    boilingPoint: 3345,
    discoveredBy: "Johan Gadolin",
    yearDiscovered: 1794,
    description: "Used in LEDs, superconductors, and cancer treatment.",
    shells: [2, 8, 18, 9, 2],
    color: "#94ffff",
    state: "solid",
  },
  {
    atomicNumber: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomicMass: 91.224,
    category: "transition-metal",
    electronConfig: "[Kr] 4d² 5s²",
    electronegativity: 1.33,
    density: 6.506,
    meltingPoint: 1855,
    boilingPoint: 4409,
    discoveredBy: "Martin Heinrich Klaproth",
    yearDiscovered: 1789,
    description: "Highly resistant to corrosion. Used in nuclear reactors and ceramics.",
    shells: [2, 8, 18, 10, 2],
    color: "#94e0e0",
    state: "solid",
  },
  {
    atomicNumber: 41,
    symbol: "Nb",
    name: "Niobium",
    atomicMass: 92.906,
    category: "transition-metal",
    electronConfig: "[Kr] 4d⁴ 5s¹",
    electronegativity: 1.6,
    density: 8.57,
    meltingPoint: 2477,
    boilingPoint: 4744,
    discoveredBy: "Charles Hatchett",
    yearDiscovered: 1801,
    description: "Used in superconducting magnets, jet engines, and surgical implants.",
    shells: [2, 8, 18, 12, 1],
    color: "#73c2c9",
    state: "solid",
  },
  {
    atomicNumber: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomicMass: 95.95,
    category: "transition-metal",
    electronConfig: "[Kr] 4d⁵ 5s¹",
    electronegativity: 2.16,
    density: 10.22,
    meltingPoint: 2623,
    boilingPoint: 4639,
    discoveredBy: "Carl Wilhelm Scheele",
    yearDiscovered: 1778,
    description: "High melting point metal used in steel alloys and catalysts.",
    shells: [2, 8, 18, 13, 1],
    color: "#54b5b5",
    state: "solid",
  },
  {
    atomicNumber: 43,
    symbol: "Tc",
    name: "Technetium",
    atomicMass: 98,
    category: "transition-metal",
    electronConfig: "[Kr] 4d⁵ 5s²",
    electronegativity: 1.9,
    density: 11.5,
    meltingPoint: 2157,
    boilingPoint: 4265,
    discoveredBy: "Emilio Segrè",
    yearDiscovered: 1937,
    description: "First artificially produced element. Used in medical imaging.",
    shells: [2, 8, 18, 13, 2],
    color: "#3b9e9e",
    state: "solid",
  },
  {
    atomicNumber: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomicMass: 101.07,
    category: "transition-metal",
    electronConfig: "[Kr] 4d⁷ 5s¹",
    electronegativity: 2.2,
    density: 12.37,
    meltingPoint: 2334,
    boilingPoint: 4150,
    discoveredBy: "Karl Ernst Claus",
    yearDiscovered: 1844,
    description: "Platinum group metal used in electronics and catalysis.",
    shells: [2, 8, 18, 15, 1],
    color: "#248f8f",
    state: "solid",
  },
  {
    atomicNumber: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomicMass: 102.91,
    category: "transition-metal",
    electronConfig: "[Kr] 4d⁸ 5s¹",
    electronegativity: 2.28,
    density: 12.41,
    meltingPoint: 1964,
    boilingPoint: 3695,
    discoveredBy: "William Hyde Wollaston",
    yearDiscovered: 1803,
    description: "Rarest precious metal. Used in catalytic converters and jewelry.",
    shells: [2, 8, 18, 16, 1],
    color: "#0a7d8c",
    state: "solid",
  },
  {
    atomicNumber: 46,
    symbol: "Pd",
    name: "Palladium",
    atomicMass: 106.42,
    category: "transition-metal",
    electronConfig: "[Kr] 4d¹⁰",
    electronegativity: 2.2,
    density: 12.02,
    meltingPoint: 1554.9,
    boilingPoint: 2963,
    discoveredBy: "William Hyde Wollaston",
    yearDiscovered: 1803,
    description: "Precious metal used in catalytic converters, electronics, and jewelry.",
    shells: [2, 8, 18, 18],
    color: "#006985",
    state: "solid",
  },
  {
    atomicNumber: 47,
    symbol: "Ag",
    name: "Silver",
    atomicMass: 107.87,
    category: "transition-metal",
    electronConfig: "[Kr] 4d¹⁰ 5s¹",
    electronegativity: 1.93,
    density: 10.501,
    meltingPoint: 961.78,
    boilingPoint: 2162,
    discoveredBy: "Ancient",
    yearDiscovered: "Ancient",
    description: "Best electrical and thermal conductor. Used in jewelry, photography, and electronics.",
    shells: [2, 8, 18, 18, 1],
    color: "#c0c0c0",
    state: "solid",
  },
  {
    atomicNumber: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomicMass: 112.41,
    category: "transition-metal",
    electronConfig: "[Kr] 4d¹⁰ 5s²",
    electronegativity: 1.69,
    density: 8.69,
    meltingPoint: 321.07,
    boilingPoint: 767,
    discoveredBy: "Karl Samuel Leberecht Hermann",
    yearDiscovered: 1817,
    description: "Toxic heavy metal used in batteries, pigments, and coatings.",
    shells: [2, 8, 18, 18, 2],
    color: "#ffd98f",
    state: "solid",
  },
  {
    atomicNumber: 49,
    symbol: "In",
    name: "Indium",
    atomicMass: 114.82,
    category: "post-transition",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p¹",
    electronegativity: 1.78,
    density: 7.31,
    meltingPoint: 156.6,
    boilingPoint: 2072,
    discoveredBy: "Ferdinand Reich",
    yearDiscovered: 1863,
    description: "Soft, malleable metal used in LCD screens, solar cells, and low-melting alloys.",
    shells: [2, 8, 18, 18, 3],
    color: "#a67573",
    state: "solid",
  },
  {
    atomicNumber: 50,
    symbol: "Sn",
    name: "Tin",
    atomicMass: 118.71,
    category: "post-transition",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p²",
    electronegativity: 1.96,
    density: 7.287,
    meltingPoint: 231.93,
    boilingPoint: 2602,
    discoveredBy: "Ancient",
    yearDiscovered: "Ancient",
    description: "Used in bronze, solder, and tin cans. Known since ancient times.",
    shells: [2, 8, 18, 18, 4],
    color: "#668080",
    state: "solid",
  },
  {
    atomicNumber: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicMass: 121.76,
    category: "metalloid",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p³",
    electronegativity: 2.05,
    density: 6.685,
    meltingPoint: 630.63,
    boilingPoint: 1587,
    discoveredBy: "Ancient",
    yearDiscovered: "Ancient",
    description: "Metalloid used in flame retardants, batteries, and semiconductors.",
    shells: [2, 8, 18, 18, 5],
    color: "#9e63b5",
    state: "solid",
  },
  {
    atomicNumber: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicMass: 127.6,
    category: "metalloid",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁴",
    electronegativity: 2.1,
    density: 6.232,
    meltingPoint: 449.51,
    boilingPoint: 988,
    discoveredBy: "Franz-Joseph Müller von Reichenstein",
    yearDiscovered: 1783,
    description: "Rare metalloid used in solar cells, thermoelectric devices, and alloys.",
    shells: [2, 8, 18, 18, 6],
    color: "#d47a00",
    state: "solid",
  },
  {
    atomicNumber: 53,
    symbol: "I",
    name: "Iodine",
    atomicMass: 126.9,
    category: "halogen",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁵",
    electronegativity: 2.66,
    density: 4.93,
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    discoveredBy: "Bernard Courtois",
    yearDiscovered: 1811,
    description: "Essential for thyroid function. Used in medicine and photography.",
    shells: [2, 8, 18, 18, 7],
    color: "#940094",
    state: "solid",
  },
  {
    atomicNumber: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicMass: 131.29,
    category: "noble-gas",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁶",
    electronegativity: 2.6,
    density: 0.005887,
    meltingPoint: -111.75,
    boilingPoint: -108.12,
    discoveredBy: "William Ramsay",
    yearDiscovered: 1898,
    description: "Noble gas used in flash lamps, ion propulsion, and anesthesia.",
    shells: [2, 8, 18, 18, 8],
    color: "#429eb0",
    state: "gas",
  },

  // Period 6
  {
    atomicNumber: 55,
    symbol: "Cs",
    name: "Cesium",
    atomicMass: 132.91,
    category: "alkali-metal",
    electronConfig: "[Xe] 6s¹",
    electronegativity: 0.79,
    density: 1.873,
    meltingPoint: 28.44,
    boilingPoint: 671,
    discoveredBy: "Robert Bunsen",
    yearDiscovered: 1860,
    description: "Most electropositive stable element. Used in atomic clocks.",
    shells: [2, 8, 18, 18, 8, 1],
    color: "#57178f",
    state: "solid",
  },
  {
    atomicNumber: 56,
    symbol: "Ba",
    name: "Barium",
    atomicMass: 137.33,
    category: "alkaline-earth",
    electronConfig: "[Xe] 6s²",
    electronegativity: 0.89,
    density: 3.594,
    meltingPoint: 727,
    boilingPoint: 1897,
    discoveredBy: "Carl Wilhelm Scheele",
    yearDiscovered: 1772,
    description: "Used in fireworks (green color), X-ray imaging, and drilling fluids.",
    shells: [2, 8, 18, 18, 8, 2],
    color: "#00c900",
    state: "solid",
  },
  // Lanthanides (57-71)
  {
    atomicNumber: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicMass: 138.91,
    category: "lanthanide",
    electronConfig: "[Xe] 5d¹ 6s²",
    electronegativity: 1.1,
    density: 6.145,
    meltingPoint: 920,
    boilingPoint: 3464,
    discoveredBy: "Carl Gustaf Mosander",
    yearDiscovered: 1839,
    description: "First lanthanide. Used in camera lenses, battery electrodes, and catalysts.",
    shells: [2, 8, 18, 18, 9, 2],
    color: "#70d4ff",
    state: "solid",
  },
  {
    atomicNumber: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicMass: 140.12,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹ 5d¹ 6s²",
    electronegativity: 1.12,
    density: 6.77,
    meltingPoint: 795,
    boilingPoint: 3443,
    discoveredBy: "Jöns Jacob Berzelius",
    yearDiscovered: 1803,
    description: "Most abundant lanthanide. Used in catalytic converters and polishing compounds.",
    shells: [2, 8, 18, 19, 9, 2],
    color: "#ffffc7",
    state: "solid",
  },
  {
    atomicNumber: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicMass: 140.91,
    category: "lanthanide",
    electronConfig: "[Xe] 4f³ 6s²",
    electronegativity: 1.13,
    density: 6.773,
    meltingPoint: 931,
    boilingPoint: 3520,
    discoveredBy: "Carl Auer von Welsbach",
    yearDiscovered: 1885,
    description: "Used in magnets, lasers, and yellow-green glass coloring.",
    shells: [2, 8, 18, 21, 8, 2],
    color: "#d9ffc7",
    state: "solid",
  },
  {
    atomicNumber: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicMass: 144.24,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁴ 6s²",
    electronegativity: 1.14,
    density: 7.007,
    meltingPoint: 1021,
    boilingPoint: 3074,
    discoveredBy: "Carl Auer von Welsbach",
    yearDiscovered: 1885,
    description: "Used in powerful permanent magnets, lasers, and glass coloring.",
    shells: [2, 8, 18, 22, 8, 2],
    color: "#c7ffc7",
    state: "solid",
  },
  {
    atomicNumber: 61,
    symbol: "Pm",
    name: "Promethium",
    atomicMass: 145,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁵ 6s²",
    electronegativity: 1.13,
    density: 7.26,
    meltingPoint: 1042,
    boilingPoint: 3000,
    discoveredBy: "Chien Shiung Wu",
    yearDiscovered: 1945,
    description: "Radioactive. Used in nuclear batteries and luminous paint.",
    shells: [2, 8, 18, 23, 8, 2],
    color: "#a3ffc7",
    state: "solid",
  },
  {
    atomicNumber: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicMass: 150.36,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁶ 6s²",
    electronegativity: 1.17,
    density: 7.52,
    meltingPoint: 1072,
    boilingPoint: 1900,
    discoveredBy: "Paul Emile Lecoq de Boisbaudran",
    yearDiscovered: 1879,
    description: "Used in magnets, cancer treatment, and nuclear reactor control rods.",
    shells: [2, 8, 18, 24, 8, 2],
    color: "#8fffc7",
    state: "solid",
  },
  {
    atomicNumber: 63,
    symbol: "Eu",
    name: "Europium",
    atomicMass: 151.96,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁷ 6s²",
    electronegativity: 1.2,
    density: 5.243,
    meltingPoint: 822,
    boilingPoint: 1529,
    discoveredBy: "Eugène-Anatole Demarçay",
    yearDiscovered: 1901,
    description: "Used in red phosphors for TVs and LEDs, and in Euro banknotes.",
    shells: [2, 8, 18, 25, 8, 2],
    color: "#61ffc7",
    state: "solid",
  },
  {
    atomicNumber: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicMass: 157.25,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁷ 5d¹ 6s²",
    electronegativity: 1.2,
    density: 7.895,
    meltingPoint: 1313,
    boilingPoint: 3273,
    discoveredBy: "Jean Charles Galissard de Marignac",
    yearDiscovered: 1880,
    description: "Used in MRI contrast agents, neutron capture, and magnets.",
    shells: [2, 8, 18, 25, 9, 2],
    color: "#45ffc7",
    state: "solid",
  },
  {
    atomicNumber: 65,
    symbol: "Tb",
    name: "Terbium",
    atomicMass: 158.93,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁹ 6s²",
    electronegativity: 1.2,
    density: 8.229,
    meltingPoint: 1356,
    boilingPoint: 3230,
    discoveredBy: "Carl Gustaf Mosander",
    yearDiscovered: 1843,
    description: "Used in green phosphors, solid-state devices, and magnets.",
    shells: [2, 8, 18, 27, 8, 2],
    color: "#30ffc7",
    state: "solid",
  },
  {
    atomicNumber: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomicMass: 162.5,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹⁰ 6s²",
    electronegativity: 1.22,
    density: 8.55,
    meltingPoint: 1412,
    boilingPoint: 2567,
    discoveredBy: "Paul Emile Lecoq de Boisbaudran",
    yearDiscovered: 1886,
    description: "Used in lasers, hard disk drives, and high-power magnets.",
    shells: [2, 8, 18, 28, 8, 2],
    color: "#1fffc7",
    state: "solid",
  },
  {
    atomicNumber: 67,
    symbol: "Ho",
    name: "Holmium",
    atomicMass: 164.93,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹¹ 6s²",
    electronegativity: 1.23,
    density: 8.795,
    meltingPoint: 1474,
    boilingPoint: 2700,
    discoveredBy: "Marc Delafontaine",
    yearDiscovered: 1878,
    description: "Highest magnetic moment of any element. Used in magnets and lasers.",
    shells: [2, 8, 18, 29, 8, 2],
    color: "#00ff9c",
    state: "solid",
  },
  {
    atomicNumber: 68,
    symbol: "Er",
    name: "Erbium",
    atomicMass: 167.26,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹² 6s²",
    electronegativity: 1.24,
    density: 9.066,
    meltingPoint: 1529,
    boilingPoint: 2868,
    discoveredBy: "Carl Gustaf Mosander",
    yearDiscovered: 1843,
    description: "Used in fiber optic amplifiers, lasers, and pink glass coloring.",
    shells: [2, 8, 18, 30, 8, 2],
    color: "#00e675",
    state: "solid",
  },
  {
    atomicNumber: 69,
    symbol: "Tm",
    name: "Thulium",
    atomicMass: 168.93,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹³ 6s²",
    electronegativity: 1.25,
    density: 9.321,
    meltingPoint: 1545,
    boilingPoint: 1950,
    discoveredBy: "Per Teodor Cleve",
    yearDiscovered: 1879,
    description: "Rarest lanthanide. Used in portable X-ray machines and lasers.",
    shells: [2, 8, 18, 31, 8, 2],
    color: "#00d452",
    state: "solid",
  },
  {
    atomicNumber: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomicMass: 173.05,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹⁴ 6s²",
    electronegativity: 1.1,
    density: 6.965,
    meltingPoint: 819,
    boilingPoint: 1196,
    discoveredBy: "Jean Charles Galissard de Marignac",
    yearDiscovered: 1878,
    description: "Used in atomic clocks, lasers, and as a stress gauge.",
    shells: [2, 8, 18, 32, 8, 2],
    color: "#00bf38",
    state: "solid",
  },
  {
    atomicNumber: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomicMass: 174.97,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹⁴ 5d¹ 6s²",
    electronegativity: 1.27,
    density: 9.84,
    meltingPoint: 1663,
    boilingPoint: 3402,
    discoveredBy: "Georges Urbain",
    yearDiscovered: 1907,
    description: "Densest and hardest lanthanide. Used in PET scanners and catalysts.",
    shells: [2, 8, 18, 32, 9, 2],
    color: "#00ab24",
    state: "solid",
  },
  // Continue Period 6
  {
    atomicNumber: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomicMass: 178.49,
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d² 6s²",
    electronegativity: 1.3,
    density: 13.31,
    meltingPoint: 2233,
    boilingPoint: 4603,
    discoveredBy: "Dirk Coster",
    yearDiscovered: 1923,
    description: "Used in nuclear control rods, jet engines, and semiconductors.",
    shells: [2, 8, 18, 32, 10, 2],
    color: "#4dc2ff",
    state: "solid",
  },
  {
    atomicNumber: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomicMass: 180.95,
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d³ 6s²",
    electronegativity: 1.5,
    density: 16.654,
    meltingPoint: 3017,
    boilingPoint: 5458,
    discoveredBy: "Anders Gustaf Ekeberg",
    yearDiscovered: 1802,
    description: "Highly corrosion-resistant. Used in electronics, surgical implants, and jet engines.",
    shells: [2, 8, 18, 32, 11, 2],
    color: "#4da6ff",
    state: "solid",
  },
  {
    atomicNumber: 74,
    symbol: "W",
    name: "Tungsten",
    atomicMass: 183.84,
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    electronegativity: 2.36,
    density: 19.25,
    meltingPoint: 3422,
    boilingPoint: 5555,
    discoveredBy: "Carl Wilhelm Scheele",
    yearDiscovered: 1783,
    description: "Highest melting point of all elements. Used in light bulb filaments and cutting tools.",
    shells: [2, 8, 18, 32, 12, 2],
    color: "#2194d6",
    state: "solid",
  },
  {
    atomicNumber: 75,
    symbol: "Re",
    name: "Rhenium",
    atomicMass: 186.21,
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    electronegativity: 1.9,
    density: 21.02,
    meltingPoint: 3186,
    boilingPoint: 5596,
    discoveredBy: "Masataka Ogawa",
    yearDiscovered: 1925,
    description: "One of rarest elements. Used in jet engines and catalysts.",
    shells: [2, 8, 18, 32, 13, 2],
    color: "#267dab",
    state: "solid",
  },
  {
    atomicNumber: 76,
    symbol: "Os",
    name: "Osmium",
    atomicMass: 190.23,
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    electronegativity: 2.2,
    density: 22.59,
    meltingPoint: 3033,
    boilingPoint: 5012,
    discoveredBy: "Smithson Tennant",
    yearDiscovered: 1803,
    description: "Densest naturally occurring element. Used in fountain pen tips and electrical contacts.",
    shells: [2, 8, 18, 32, 14, 2],
    color: "#266696",
    state: "solid",
  },
  {
    atomicNumber: 77,
    symbol: "Ir",
    name: "Iridium",
    atomicMass: 192.22,
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    electronegativity: 2.2,
    density: 22.56,
    meltingPoint: 2446,
    boilingPoint: 4428,
    discoveredBy: "Smithson Tennant",
    yearDiscovered: 1803,
    description: "Most corrosion-resistant metal. Used in spark plugs and crucibles.",
    shells: [2, 8, 18, 32, 15, 2],
    color: "#175487",
    state: "solid",
  },
  {
    atomicNumber: 78,
    symbol: "Pt",
    name: "Platinum",
    atomicMass: 195.08,
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    electronegativity: 2.28,
    density: 21.46,
    meltingPoint: 1768.3,
    boilingPoint: 3825,
    discoveredBy: "Antonio de Ulloa",
    yearDiscovered: 1735,
    description: "Precious metal used in catalytic converters, jewelry, and laboratory equipment.",
    shells: [2, 8, 18, 32, 17, 1],
    color: "#d0d0e0",
    state: "solid",
  },
  {
    atomicNumber: 79,
    symbol: "Au",
    name: "Gold",
    atomicMass: 196.97,
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    electronegativity: 2.54,
    density: 19.282,
    meltingPoint: 1064.18,
    boilingPoint: 2856,
    discoveredBy: "Ancient",
    yearDiscovered: "Ancient",
    description: "Precious metal prized since antiquity. Used in jewelry, electronics, and currency.",
    shells: [2, 8, 18, 32, 18, 1],
    color: "#ffd123",
    state: "solid",
  },
  {
    atomicNumber: 80,
    symbol: "Hg",
    name: "Mercury",
    atomicMass: 200.59,
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    electronegativity: 2.0,
    density: 13.5336,
    meltingPoint: -38.83,
    boilingPoint: 356.73,
    discoveredBy: "Ancient",
    yearDiscovered: "Ancient",
    description: "Only metal liquid at room temperature. Used in thermometers and barometers.",
    shells: [2, 8, 18, 32, 18, 2],
    color: "#b8b8d0",
    state: "liquid",
  },
  {
    atomicNumber: 81,
    symbol: "Tl",
    name: "Thallium",
    atomicMass: 204.38,
    category: "post-transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    electronegativity: 1.62,
    density: 11.85,
    meltingPoint: 304,
    boilingPoint: 1473,
    discoveredBy: "William Crookes",
    yearDiscovered: 1861,
    description: "Highly toxic metal. Used in electronics, glass, and medicine.",
    shells: [2, 8, 18, 32, 18, 3],
    color: "#a6544d",
    state: "solid",
  },
  {
    atomicNumber: 82,
    symbol: "Pb",
    name: "Lead",
    atomicMass: 207.2,
    category: "post-transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    electronegativity: 1.87,
    density: 11.342,
    meltingPoint: 327.46,
    boilingPoint: 1749,
    discoveredBy: "Ancient",
    yearDiscovered: "Ancient",
    description: "Dense, soft metal. Used in batteries, radiation shielding, and historically in pipes.",
    shells: [2, 8, 18, 32, 18, 4],
    color: "#575961",
    state: "solid",
  },
  {
    atomicNumber: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomicMass: 208.98,
    category: "post-transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    electronegativity: 2.02,
    density: 9.807,
    meltingPoint: 271.3,
    boilingPoint: 1564,
    discoveredBy: "Claude François Geoffroy",
    yearDiscovered: 1753,
    description: "Diamagnetic metal with low toxicity. Used in cosmetics, medicine, and alloys.",
    shells: [2, 8, 18, 32, 18, 5],
    color: "#9e4fb5",
    state: "solid",
  },
  {
    atomicNumber: 84,
    symbol: "Po",
    name: "Polonium",
    atomicMass: 209,
    category: "metalloid",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    electronegativity: 2.0,
    density: 9.32,
    meltingPoint: 254,
    boilingPoint: 962,
    discoveredBy: "Marie Curie",
    yearDiscovered: 1898,
    description: "Highly radioactive. Used in anti-static devices and as a heat source.",
    shells: [2, 8, 18, 32, 18, 6],
    color: "#ab5c00",
    state: "solid",
  },
  {
    atomicNumber: 85,
    symbol: "At",
    name: "Astatine",
    atomicMass: 210,
    category: "halogen",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    electronegativity: 2.2,
    density: 7,
    meltingPoint: 302,
    boilingPoint: 337,
    discoveredBy: "Dale R. Corson",
    yearDiscovered: 1940,
    description: "Rarest naturally occurring element. Radioactive halogen with potential medical uses.",
    shells: [2, 8, 18, 32, 18, 7],
    color: "#754f45",
    state: "solid",
  },
  {
    atomicNumber: 86,
    symbol: "Rn",
    name: "Radon",
    atomicMass: 222,
    category: "noble-gas",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    electronegativity: 2.2,
    density: 0.00973,
    meltingPoint: -71,
    boilingPoint: -61.7,
    discoveredBy: "Friedrich Ernst Dorn",
    yearDiscovered: 1900,
    description: "Radioactive noble gas. Second leading cause of lung cancer.",
    shells: [2, 8, 18, 32, 18, 8],
    color: "#428296",
    state: "gas",
  },

  // Period 7
  {
    atomicNumber: 87,
    symbol: "Fr",
    name: "Francium",
    atomicMass: 223,
    category: "alkali-metal",
    electronConfig: "[Rn] 7s¹",
    electronegativity: 0.79,
    density: 1.87,
    meltingPoint: 27,
    boilingPoint: 677,
    discoveredBy: "Marguerite Perey",
    yearDiscovered: 1939,
    description: "Most unstable natural element. Highly radioactive alkali metal.",
    shells: [2, 8, 18, 32, 18, 8, 1],
    color: "#420066",
    state: "solid",
  },
  {
    atomicNumber: 88,
    symbol: "Ra",
    name: "Radium",
    atomicMass: 226,
    category: "alkaline-earth",
    electronConfig: "[Rn] 7s²",
    electronegativity: 0.9,
    density: 5.5,
    meltingPoint: 700,
    boilingPoint: 1737,
    discoveredBy: "Marie Curie",
    yearDiscovered: 1898,
    description: "Radioactive element that glows blue. Historically used in luminous paint.",
    shells: [2, 8, 18, 32, 18, 8, 2],
    color: "#007d00",
    state: "solid",
  },
  // Actinides (89-103)
  {
    atomicNumber: 89,
    symbol: "Ac",
    name: "Actinium",
    atomicMass: 227,
    category: "actinide",
    electronConfig: "[Rn] 6d¹ 7s²",
    electronegativity: 1.1,
    density: 10.07,
    meltingPoint: 1050,
    boilingPoint: 3200,
    discoveredBy: "Friedrich Oskar Giesel",
    yearDiscovered: 1899,
    description: "First actinide. Radioactive, glows blue in the dark.",
    shells: [2, 8, 18, 32, 18, 9, 2],
    color: "#70abfa",
    state: "solid",
  },
  {
    atomicNumber: 90,
    symbol: "Th",
    name: "Thorium",
    atomicMass: 232.04,
    category: "actinide",
    electronConfig: "[Rn] 6d² 7s²",
    electronegativity: 1.3,
    density: 11.72,
    meltingPoint: 1750,
    boilingPoint: 4788,
    discoveredBy: "Jöns Jacob Berzelius",
    yearDiscovered: 1829,
    description: "Radioactive metal, potential nuclear fuel. Used in gas mantles.",
    shells: [2, 8, 18, 32, 18, 10, 2],
    color: "#00baff",
    state: "solid",
  },
  {
    atomicNumber: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomicMass: 231.04,
    category: "actinide",
    electronConfig: "[Rn] 5f² 6d¹ 7s²",
    electronegativity: 1.5,
    density: 15.37,
    meltingPoint: 1572,
    boilingPoint: 4000,
    discoveredBy: "Kasimir Fajans",
    yearDiscovered: 1913,
    description: "Rare, toxic, radioactive. One of the rarest natural elements.",
    shells: [2, 8, 18, 32, 20, 9, 2],
    color: "#00a1ff",
    state: "solid",
  },
  {
    atomicNumber: 92,
    symbol: "U",
    name: "Uranium",
    atomicMass: 238.03,
    category: "actinide",
    electronConfig: "[Rn] 5f³ 6d¹ 7s²",
    electronegativity: 1.38,
    density: 18.95,
    meltingPoint: 1135,
    boilingPoint: 4131,
    discoveredBy: "Martin Heinrich Klaproth",
    yearDiscovered: 1789,
    description: "Nuclear fuel. Used in weapons, power plants, and as radiation shielding.",
    shells: [2, 8, 18, 32, 21, 9, 2],
    color: "#008fff",
    state: "solid",
  },
  {
    atomicNumber: 93,
    symbol: "Np",
    name: "Neptunium",
    atomicMass: 237,
    category: "actinide",
    electronConfig: "[Rn] 5f⁴ 6d¹ 7s²",
    electronegativity: 1.36,
    density: 20.45,
    meltingPoint: 644,
    boilingPoint: 4000,
    discoveredBy: "Edwin McMillan",
    yearDiscovered: 1940,
    description: "First transuranium element. Radioactive, used in neutron detection.",
    shells: [2, 8, 18, 32, 22, 9, 2],
    color: "#0080ff",
    state: "solid",
  },
  {
    atomicNumber: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomicMass: 244,
    category: "actinide",
    electronConfig: "[Rn] 5f⁶ 7s²",
    electronegativity: 1.28,
    density: 19.84,
    meltingPoint: 640,
    boilingPoint: 3228,
    discoveredBy: "Glenn T. Seaborg",
    yearDiscovered: 1940,
    description: "Used in nuclear weapons and reactors. Named after Pluto.",
    shells: [2, 8, 18, 32, 24, 8, 2],
    color: "#006bff",
    state: "solid",
  },
  {
    atomicNumber: 95,
    symbol: "Am",
    name: "Americium",
    atomicMass: 243,
    category: "actinide",
    electronConfig: "[Rn] 5f⁷ 7s²",
    electronegativity: 1.13,
    density: 13.69,
    meltingPoint: 1176,
    boilingPoint: 2011,
    discoveredBy: "Glenn T. Seaborg",
    yearDiscovered: 1944,
    description: "Used in smoke detectors and as a neutron source.",
    shells: [2, 8, 18, 32, 25, 8, 2],
    color: "#545cf2",
    state: "solid",
  },
  {
    atomicNumber: 96,
    symbol: "Cm",
    name: "Curium",
    atomicMass: 247,
    category: "actinide",
    electronConfig: "[Rn] 5f⁷ 6d¹ 7s²",
    electronegativity: 1.28,
    density: 13.51,
    meltingPoint: 1345,
    boilingPoint: 3110,
    discoveredBy: "Glenn T. Seaborg",
    yearDiscovered: 1944,
    description: "Named after Marie and Pierre Curie. Used in space exploration.",
    shells: [2, 8, 18, 32, 25, 9, 2],
    color: "#785ce3",
    state: "solid",
  },
  {
    atomicNumber: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomicMass: 247,
    category: "actinide",
    electronConfig: "[Rn] 5f⁹ 7s²",
    electronegativity: 1.3,
    density: 14.79,
    meltingPoint: 986,
    boilingPoint: 2627,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    yearDiscovered: 1949,
    description: "Named after Berkeley, California. Used in scientific research.",
    shells: [2, 8, 18, 32, 27, 8, 2],
    color: "#8a4fe3",
    state: "solid",
  },
  {
    atomicNumber: 98,
    symbol: "Cf",
    name: "Californium",
    atomicMass: 251,
    category: "actinide",
    electronConfig: "[Rn] 5f¹⁰ 7s²",
    electronegativity: 1.3,
    density: 15.1,
    meltingPoint: 900,
    boilingPoint: 1470,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    yearDiscovered: 1950,
    description: "Strong neutron emitter. Used in nuclear reactors and cancer treatment.",
    shells: [2, 8, 18, 32, 28, 8, 2],
    color: "#a136d4",
    state: "solid",
  },
  {
    atomicNumber: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomicMass: 252,
    category: "actinide",
    electronConfig: "[Rn] 5f¹¹ 7s²",
    electronegativity: 1.3,
    density: 8.84,
    meltingPoint: 860,
    boilingPoint: 996,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    yearDiscovered: 1952,
    description: "Named after Albert Einstein. Discovered in nuclear fallout.",
    shells: [2, 8, 18, 32, 29, 8, 2],
    color: "#b31fd4",
    state: "solid",
  },
  {
    atomicNumber: 100,
    symbol: "Fm",
    name: "Fermium",
    atomicMass: 257,
    category: "actinide",
    electronConfig: "[Rn] 5f¹² 7s²",
    electronegativity: 1.3,
    density: 9.7,
    meltingPoint: 1527,
    boilingPoint: null,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    yearDiscovered: 1952,
    description: "Named after Enrico Fermi. Discovered in hydrogen bomb debris.",
    shells: [2, 8, 18, 32, 30, 8, 2],
    color: "#b31fba",
    state: "solid",
  },
  {
    atomicNumber: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomicMass: 258,
    category: "actinide",
    electronConfig: "[Rn] 5f¹³ 7s²",
    electronegativity: 1.3,
    density: 10.3,
    meltingPoint: 827,
    boilingPoint: null,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    yearDiscovered: 1955,
    description: "Named after Dmitri Mendeleev. Only made in tiny amounts.",
    shells: [2, 8, 18, 32, 31, 8, 2],
    color: "#b30da6",
    state: "solid",
  },
  {
    atomicNumber: 102,
    symbol: "No",
    name: "Nobelium",
    atomicMass: 259,
    category: "actinide",
    electronConfig: "[Rn] 5f¹⁴ 7s²",
    electronegativity: 1.3,
    density: 9.9,
    meltingPoint: 827,
    boilingPoint: null,
    discoveredBy: "Joint Institute for Nuclear Research",
    yearDiscovered: 1958,
    description: "Named after Alfred Nobel. Very unstable with short half-life.",
    shells: [2, 8, 18, 32, 32, 8, 2],
    color: "#bd0d87",
    state: "solid",
  },
  {
    atomicNumber: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomicMass: 262,
    category: "actinide",
    electronConfig: "[Rn] 5f¹⁴ 7s² 7p¹",
    electronegativity: 1.3,
    density: 15.6,
    meltingPoint: 1627,
    boilingPoint: null,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    yearDiscovered: 1961,
    description: "Last actinide. Named after Ernest Lawrence, inventor of cyclotron.",
    shells: [2, 8, 18, 32, 32, 8, 3],
    color: "#c70066",
    state: "solid",
  },
  // Continue Period 7
  {
    atomicNumber: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomicMass: 267,
    category: "transition-metal",
    electronConfig: "[Rn] 5f¹⁴ 6d² 7s²",
    electronegativity: null,
    density: 23.2,
    meltingPoint: 2100,
    boilingPoint: 5500,
    discoveredBy: "Joint Institute for Nuclear Research",
    yearDiscovered: 1964,
    description: "Named after Ernest Rutherford. Highly radioactive synthetic element.",
    shells: [2, 8, 18, 32, 32, 10, 2],
    color: "#cc0059",
    state: "solid",
  },
  {
    atomicNumber: 105,
    symbol: "Db",
    name: "Dubnium",
    atomicMass: 268,
    category: "transition-metal",
    electronConfig: "[Rn] 5f¹⁴ 6d³ 7s²",
    electronegativity: null,
    density: 29.3,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Joint Institute for Nuclear Research",
    yearDiscovered: 1967,
    description: "Named after Dubna, Russia. Highly radioactive synthetic element.",
    shells: [2, 8, 18, 32, 32, 11, 2],
    color: "#d1004f",
    state: "unknown",
  },
  {
    atomicNumber: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomicMass: 269,
    category: "transition-metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    electronegativity: null,
    density: 35.0,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    yearDiscovered: 1974,
    description: "Named after Glenn Seaborg. Highly radioactive synthetic element.",
    shells: [2, 8, 18, 32, 32, 12, 2],
    color: "#d90045",
    state: "unknown",
  },
  {
    atomicNumber: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomicMass: 270,
    category: "transition-metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    electronegativity: null,
    density: 37.1,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    yearDiscovered: 1981,
    description: "Named after Niels Bohr. Highly radioactive synthetic element.",
    shells: [2, 8, 18, 32, 32, 13, 2],
    color: "#e00038",
    state: "unknown",
  },
  {
    atomicNumber: 108,
    symbol: "Hs",
    name: "Hassium",
    atomicMass: 277,
    category: "transition-metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    electronegativity: null,
    density: 40.7,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    yearDiscovered: 1984,
    description: "Named after Hesse, Germany. Highly radioactive synthetic element.",
    shells: [2, 8, 18, 32, 32, 14, 2],
    color: "#e6002e",
    state: "unknown",
  },
  {
    atomicNumber: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomicMass: 278,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    electronegativity: null,
    density: 37.4,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    yearDiscovered: 1982,
    description: "Named after Lise Meitner. Highly radioactive synthetic element.",
    shells: [2, 8, 18, 32, 32, 15, 2],
    color: "#eb0026",
    state: "unknown",
  },
  {
    atomicNumber: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomicMass: 281,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d⁸ 7s²",
    electronegativity: null,
    density: 34.8,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    yearDiscovered: 1994,
    description: "Named after Darmstadt, Germany. Highly radioactive synthetic element.",
    shells: [2, 8, 18, 32, 32, 16, 2],
    color: "#ffffff",
    state: "unknown",
  },
  {
    atomicNumber: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomicMass: 282,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d⁹ 7s²",
    electronegativity: null,
    density: 28.7,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    yearDiscovered: 1994,
    description: "Named after Wilhelm Röntgen. Highly radioactive synthetic element.",
    shells: [2, 8, 18, 32, 32, 17, 2],
    color: "#ffffff",
    state: "unknown",
  },
  {
    atomicNumber: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomicMass: 285,
    category: "transition-metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    electronegativity: null,
    density: 23.7,
    meltingPoint: null,
    boilingPoint: 84,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    yearDiscovered: 1996,
    description: "Named after Nicolaus Copernicus. May be a liquid at room temperature.",
    shells: [2, 8, 18, 32, 32, 18, 2],
    color: "#ffffff",
    state: "unknown",
  },
  {
    atomicNumber: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomicMass: 286,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    electronegativity: null,
    density: 16,
    meltingPoint: 430,
    boilingPoint: 1100,
    discoveredBy: "RIKEN",
    yearDiscovered: 2004,
    description: "Named after Japan (Nihon). First element discovered in Asia.",
    shells: [2, 8, 18, 32, 32, 18, 3],
    color: "#ffffff",
    state: "unknown",
  },
  {
    atomicNumber: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomicMass: 289,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    electronegativity: null,
    density: 14,
    meltingPoint: -73,
    boilingPoint: 107,
    discoveredBy: "Joint Institute for Nuclear Research",
    yearDiscovered: 1998,
    description: "Named after Flerov Laboratory. May behave like a noble gas.",
    shells: [2, 8, 18, 32, 32, 18, 4],
    color: "#ffffff",
    state: "unknown",
  },
  {
    atomicNumber: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomicMass: 290,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    electronegativity: null,
    density: 13.5,
    meltingPoint: 400,
    boilingPoint: 1100,
    discoveredBy: "Joint Institute for Nuclear Research",
    yearDiscovered: 2003,
    description: "Named after Moscow. Highly radioactive synthetic element.",
    shells: [2, 8, 18, 32, 32, 18, 5],
    color: "#ffffff",
    state: "unknown",
  },
  {
    atomicNumber: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomicMass: 293,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    electronegativity: null,
    density: 12.9,
    meltingPoint: 364,
    boilingPoint: 762,
    discoveredBy: "Joint Institute for Nuclear Research",
    yearDiscovered: 2000,
    description: "Named after Lawrence Livermore National Laboratory.",
    shells: [2, 8, 18, 32, 32, 18, 6],
    color: "#ffffff",
    state: "unknown",
  },
  {
    atomicNumber: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomicMass: 294,
    category: "halogen",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    electronegativity: null,
    density: 7.2,
    meltingPoint: 350,
    boilingPoint: 550,
    discoveredBy: "Joint Institute for Nuclear Research",
    yearDiscovered: 2010,
    description: "Named after Tennessee. Most recently discovered halogen.",
    shells: [2, 8, 18, 32, 32, 18, 7],
    color: "#ffffff",
    state: "unknown",
  },
  {
    atomicNumber: 118,
    symbol: "Og",
    name: "Oganesson",
    atomicMass: 294,
    category: "noble-gas",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    electronegativity: null,
    density: 5,
    meltingPoint: null,
    boilingPoint: 80,
    discoveredBy: "Joint Institute for Nuclear Research",
    yearDiscovered: 2002,
    description: "Named after Yuri Oganessian. Heaviest known element.",
    shells: [2, 8, 18, 32, 32, 18, 8],
    color: "#ffffff",
    state: "unknown",
  },
]

// Periodic table layout positions (row, col)
export const tableLayout: Record<number, [number, number]> = {
  // Period 1
  1: [0, 0],
  2: [0, 17],
  // Period 2
  3: [1, 0],
  4: [1, 1],
  5: [1, 12],
  6: [1, 13],
  7: [1, 14],
  8: [1, 15],
  9: [1, 16],
  10: [1, 17],
  // Period 3
  11: [2, 0],
  12: [2, 1],
  13: [2, 12],
  14: [2, 13],
  15: [2, 14],
  16: [2, 15],
  17: [2, 16],
  18: [2, 17],
  // Period 4
  19: [3, 0],
  20: [3, 1],
  21: [3, 2],
  22: [3, 3],
  23: [3, 4],
  24: [3, 5],
  25: [3, 6],
  26: [3, 7],
  27: [3, 8],
  28: [3, 9],
  29: [3, 10],
  30: [3, 11],
  31: [3, 12],
  32: [3, 13],
  33: [3, 14],
  34: [3, 15],
  35: [3, 16],
  36: [3, 17],
  // Period 5
  37: [4, 0],
  38: [4, 1],
  39: [4, 2],
  40: [4, 3],
  41: [4, 4],
  42: [4, 5],
  43: [4, 6],
  44: [4, 7],
  45: [4, 8],
  46: [4, 9],
  47: [4, 10],
  48: [4, 11],
  49: [4, 12],
  50: [4, 13],
  51: [4, 14],
  52: [4, 15],
  53: [4, 16],
  54: [4, 17],
  // Period 6
  55: [5, 0],
  56: [5, 1],
  72: [5, 3],
  73: [5, 4],
  74: [5, 5],
  75: [5, 6],
  76: [5, 7],
  77: [5, 8],
  78: [5, 9],
  79: [5, 10],
  80: [5, 11],
  81: [5, 12],
  82: [5, 13],
  83: [5, 14],
  84: [5, 15],
  85: [5, 16],
  86: [5, 17],
  // Period 7
  87: [6, 0],
  88: [6, 1],
  104: [6, 3],
  105: [6, 4],
  106: [6, 5],
  107: [6, 6],
  108: [6, 7],
  109: [6, 8],
  110: [6, 9],
  111: [6, 10],
  112: [6, 11],
  113: [6, 12],
  114: [6, 13],
  115: [6, 14],
  116: [6, 15],
  117: [6, 16],
  118: [6, 17],
  // Lanthanides (row 8)
  57: [8, 3],
  58: [8, 4],
  59: [8, 5],
  60: [8, 6],
  61: [8, 7],
  62: [8, 8],
  63: [8, 9],
  64: [8, 10],
  65: [8, 11],
  66: [8, 12],
  67: [8, 13],
  68: [8, 14],
  69: [8, 15],
  70: [8, 16],
  71: [8, 17],
  // Actinides (row 9)
  89: [9, 3],
  90: [9, 4],
  91: [9, 5],
  92: [9, 6],
  93: [9, 7],
  94: [9, 8],
  95: [9, 9],
  96: [9, 10],
  97: [9, 11],
  98: [9, 12],
  99: [9, 13],
  100: [9, 14],
  101: [9, 15],
  102: [9, 16],
  103: [9, 17],
}
