// Complete molecular data with 3D coordinates, bond information, and properties

export interface Atom {
  element: string
  position: [number, number, number]
  color: string
  radius: number
}

export interface Bond {
  atom1: number
  atom2: number
  order: 1 | 2 | 3
}

export interface Molecule {
  id: string
  name: string
  formula: string
  molecularWeight: number
  description: string
  category: "organic" | "inorganic" | "biological" | "polymer" | "pharmaceutical" | "industrial" | "metal" | "gas"
  atoms: Atom[]
  bonds: Bond[]
  properties: {
    meltingPoint?: string
    boilingPoint?: string
    density?: string
    solubility?: string
    polarity?: "polar" | "nonpolar" | "amphiphilic"
    bondAngles?: string[]
    uses?: string[]
  }
}

// Element colors and radii (CPK coloring) with vibrant colors
export const elementProperties: Record<string, { color: string; radius: number; name: string }> = {
  H: { color: "#FFFFFF", radius: 0.31, name: "Hydrogen" },
  C: { color: "#909090", radius: 0.77, name: "Carbon" },
  N: { color: "#3050F8", radius: 0.71, name: "Nitrogen" },
  O: { color: "#FF0D0D", radius: 0.66, name: "Oxygen" },
  F: { color: "#90E050", radius: 0.57, name: "Fluorine" },
  Cl: { color: "#1FF01F", radius: 0.99, name: "Chlorine" },
  Br: { color: "#A62929", radius: 1.14, name: "Bromine" },
  I: { color: "#940094", radius: 1.33, name: "Iodine" },
  S: { color: "#FFFF30", radius: 1.05, name: "Sulfur" },
  P: { color: "#FF8000", radius: 1.07, name: "Phosphorus" },
  Na: { color: "#AB5CF2", radius: 1.86, name: "Sodium" },
  K: { color: "#8F40D4", radius: 2.27, name: "Potassium" },
  Ca: { color: "#3DFF00", radius: 1.97, name: "Calcium" },
  Mg: { color: "#8AFF00", radius: 1.45, name: "Magnesium" },
  Fe: { color: "#E06633", radius: 1.26, name: "Iron" },
  Zn: { color: "#7D80B0", radius: 1.22, name: "Zinc" },
  Cu: { color: "#C88033", radius: 1.28, name: "Copper" },
  Si: { color: "#F0C8A0", radius: 1.11, name: "Silicon" },
  Al: { color: "#BFA6A6", radius: 1.21, name: "Aluminum" },
  B: { color: "#FFB5B5", radius: 0.82, name: "Boron" },
  Li: { color: "#CC80FF", radius: 1.28, name: "Lithium" },
  He: { color: "#D9FFFF", radius: 0.28, name: "Helium" },
  Ne: { color: "#B3E3F5", radius: 0.38, name: "Neon" },
  Ar: { color: "#80D1E3", radius: 0.71, name: "Argon" },
  Au: { color: "#FFD123", radius: 1.44, name: "Gold" },
  Ag: { color: "#C0C0C0", radius: 1.44, name: "Silver" },
  Pt: { color: "#D0D0E0", radius: 1.39, name: "Platinum" },
  Hg: { color: "#B8B8D0", radius: 1.51, name: "Mercury" },
  Pb: { color: "#575961", radius: 1.75, name: "Lead" },
  Sn: { color: "#668080", radius: 1.45, name: "Tin" },
  Ti: { color: "#BFC2C7", radius: 1.47, name: "Titanium" },
  Cr: { color: "#8A99C7", radius: 1.29, name: "Chromium" },
  Mn: { color: "#9C7AC7", radius: 1.35, name: "Manganese" },
  Co: { color: "#F090A0", radius: 1.26, name: "Cobalt" },
  Ni: { color: "#50D050", radius: 1.24, name: "Nickel" },
  W: { color: "#2194D6", radius: 1.41, name: "Tungsten" },
  Mo: { color: "#54B5B5", radius: 1.45, name: "Molybdenum" },
  V: { color: "#A6A6AB", radius: 1.34, name: "Vanadium" },
  Pd: { color: "#006985", radius: 1.37, name: "Palladium" },
  Rh: { color: "#0A7D8C", radius: 1.34, name: "Rhodium" },
  Ru: { color: "#248F8F", radius: 1.34, name: "Ruthenium" },
  Os: { color: "#266696", radius: 1.35, name: "Osmium" },
  Ir: { color: "#175487", radius: 1.36, name: "Iridium" },
  Se: { color: "#FFA100", radius: 1.2, name: "Selenium" },
  Te: { color: "#D47A00", radius: 1.38, name: "Tellurium" },
  As: { color: "#BD80E3", radius: 1.19, name: "Arsenic" },
  Sb: { color: "#9E63B5", radius: 1.39, name: "Antimony" },
  Bi: { color: "#9E4FB5", radius: 1.48, name: "Bismuth" },
  Ba: { color: "#00C900", radius: 2.22, name: "Barium" },
  Sr: { color: "#00FF00", radius: 2.15, name: "Strontium" },
  Cs: { color: "#57178F", radius: 2.67, name: "Cesium" },
  Rb: { color: "#702EB0", radius: 2.48, name: "Rubidium" },
}

// Category info with colors - added metal and gas categories
export const categoryInfo: Record<string, { color: string; label: string; icon: string }> = {
  organic: { color: "#22c55e", label: "Organic", icon: "🌿" },
  inorganic: { color: "#3b82f6", label: "Inorganic", icon: "💎" },
  biological: { color: "#ec4899", label: "Biological", icon: "🧬" },
  polymer: { color: "#f97316", label: "Polymer", icon: "🔗" },
  pharmaceutical: { color: "#8b5cf6", label: "Pharmaceutical", icon: "💊" },
  industrial: { color: "#06b6d4", label: "Industrial", icon: "🏭" },
  metal: { color: "#fbbf24", label: "Metallic", icon: "⚙️" },
  gas: { color: "#a855f7", label: "Gases", icon: "💨" },
}

export const molecules: Molecule[] = [
  // ============ INORGANIC MOLECULES ============
  {
    id: "water",
    name: "Water",
    formula: "H₂O",
    molecularWeight: 18.015,
    description: "The most essential molecule for life. Water has unique properties due to hydrogen bonding.",
    category: "inorganic",
    atoms: [
      { element: "O", position: [0, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [0.96, 0, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-0.24, 0.93, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 0, atom2: 2, order: 1 },
    ],
    properties: {
      meltingPoint: "0°C",
      boilingPoint: "100°C",
      density: "1.0 g/cm³",
      polarity: "polar",
      bondAngles: ["H-O-H: 104.5°"],
      uses: ["Drinking", "Agriculture", "Industry", "Biological processes"],
    },
  },
  {
    id: "co2",
    name: "Carbon Dioxide",
    formula: "CO₂",
    molecularWeight: 44.01,
    description: "A linear molecule essential for photosynthesis and a major greenhouse gas.",
    category: "inorganic",
    atoms: [
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [-1.16, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [1.16, 0, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 0, atom2: 2, order: 2 },
    ],
    properties: {
      meltingPoint: "-78.5°C (sublimes)",
      boilingPoint: "-56.6°C (at 5.1 atm)",
      density: "1.98 g/L",
      polarity: "nonpolar",
      bondAngles: ["O-C-O: 180°"],
      uses: ["Carbonated drinks", "Fire extinguishers", "Photosynthesis", "Dry ice"],
    },
  },
  {
    id: "ammonia",
    name: "Ammonia",
    formula: "NH₃",
    molecularWeight: 17.03,
    description: "A pungent gas with a trigonal pyramidal structure. Important in fertilizer production.",
    category: "inorganic",
    atoms: [
      { element: "N", position: [0, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "H", position: [0.94, 0.33, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-0.47, 0.33, 0.81], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-0.47, 0.33, -0.81], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
    ],
    properties: {
      meltingPoint: "-77.7°C",
      boilingPoint: "-33.3°C",
      density: "0.73 g/L",
      polarity: "polar",
      bondAngles: ["H-N-H: 107°"],
      uses: ["Fertilizers", "Cleaning products", "Refrigerant", "Explosives"],
    },
  },
  {
    id: "sodium-chloride",
    name: "Sodium Chloride",
    formula: "NaCl",
    molecularWeight: 58.44,
    description: "Common table salt - an ionic compound essential for life.",
    category: "inorganic",
    atoms: [
      { element: "Na", position: [-1.4, 0, 0], color: "#AB5CF2", radius: 1.86 },
      { element: "Cl", position: [1.4, 0, 0], color: "#1FF01F", radius: 0.99 },
    ],
    bonds: [{ atom1: 0, atom2: 1, order: 1 }],
    properties: {
      meltingPoint: "801°C",
      boilingPoint: "1465°C",
      density: "2.16 g/cm³",
      polarity: "polar",
      uses: ["Food seasoning", "Preservation", "De-icing", "Chemical production"],
    },
  },
  {
    id: "hydrochloric-acid",
    name: "Hydrochloric Acid",
    formula: "HCl",
    molecularWeight: 36.46,
    description: "A strong acid found in gastric juice and used in industry.",
    category: "inorganic",
    atoms: [
      { element: "H", position: [-0.64, 0, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "Cl", position: [0.64, 0, 0], color: "#1FF01F", radius: 0.99 },
    ],
    bonds: [{ atom1: 0, atom2: 1, order: 1 }],
    properties: {
      meltingPoint: "-114.2°C",
      boilingPoint: "-85°C",
      density: "1.49 g/L",
      polarity: "polar",
      uses: ["pH control", "Digestion", "Cleaning", "Chemical synthesis"],
    },
  },
  {
    id: "sulfuric-acid",
    name: "Sulfuric Acid",
    formula: "H₂SO₄",
    molecularWeight: 98.079,
    description: "One of the most important industrial chemicals.",
    category: "industrial",
    atoms: [
      { element: "S", position: [0, 0, 0], color: "#FFFF30", radius: 1.05 },
      { element: "O", position: [1.2, 0.8, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-1.2, 0.8, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [0.8, -1.2, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-0.8, -1.2, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [1.6, -1.5, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.6, -1.5, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 0, atom2: 2, order: 2 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 0, atom2: 4, order: 1 },
      { atom1: 3, atom2: 5, order: 1 },
      { atom1: 4, atom2: 6, order: 1 },
    ],
    properties: {
      meltingPoint: "10°C",
      boilingPoint: "337°C",
      density: "1.84 g/cm³",
      polarity: "polar",
      uses: ["Batteries", "Fertilizers", "Oil refining", "Chemical synthesis"],
    },
  },
  // ============ ORGANIC MOLECULES ============
  {
    id: "methane",
    name: "Methane",
    formula: "CH₄",
    molecularWeight: 16.04,
    description: "The simplest alkane and primary component of natural gas.",
    category: "organic",
    atoms: [
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "H", position: [0.63, 0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-0.63, -0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-0.63, 0.63, -0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [0.63, -0.63, -0.63], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 0, atom2: 4, order: 1 },
    ],
    properties: {
      meltingPoint: "-182.5°C",
      boilingPoint: "-161.5°C",
      density: "0.657 g/L",
      polarity: "nonpolar",
      bondAngles: ["H-C-H: 109.5°"],
      uses: ["Natural gas", "Fuel", "Chemical synthesis"],
    },
  },
  {
    id: "ethanol",
    name: "Ethanol",
    formula: "C₂H₅OH",
    molecularWeight: 46.07,
    description: "Drinking alcohol, also used as fuel and solvent.",
    category: "organic",
    atoms: [
      { element: "C", position: [-0.77, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0.77, 0, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [1.4, 1.2, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [-1.17, 0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.17, -0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.17, 0, -0.89], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.17, -0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.17, -0.63, -0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [2.3, 1.4, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 0, atom2: 4, order: 1 },
      { atom1: 0, atom2: 5, order: 1 },
      { atom1: 1, atom2: 6, order: 1 },
      { atom1: 1, atom2: 7, order: 1 },
      { atom1: 2, atom2: 8, order: 1 },
    ],
    properties: {
      meltingPoint: "-114°C",
      boilingPoint: "78.4°C",
      density: "0.789 g/cm³",
      polarity: "polar",
      uses: ["Beverages", "Fuel", "Disinfectant", "Solvent"],
    },
  },
  {
    id: "acetone",
    name: "Acetone",
    formula: "C₃H₆O",
    molecularWeight: 58.08,
    description: "Common solvent, nail polish remover component.",
    category: "organic",
    atoms: [
      { element: "C", position: [-1.2, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.2, 0, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [0, 1.2, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [-1.6, 0.6, 0.6], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.6, -0.6, 0.6], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.6, 0, -0.8], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.6, 0.6, 0.6], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.6, -0.6, 0.6], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.6, 0, -0.8], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 1, atom2: 3, order: 2 },
      { atom1: 0, atom2: 4, order: 1 },
      { atom1: 0, atom2: 5, order: 1 },
      { atom1: 0, atom2: 6, order: 1 },
      { atom1: 2, atom2: 7, order: 1 },
      { atom1: 2, atom2: 8, order: 1 },
      { atom1: 2, atom2: 9, order: 1 },
    ],
    properties: {
      meltingPoint: "-95°C",
      boilingPoint: "56°C",
      density: "0.79 g/cm³",
      polarity: "polar",
      uses: ["Solvent", "Nail polish remover", "Paint thinner"],
    },
  },
  {
    id: "benzene",
    name: "Benzene",
    formula: "C₆H₆",
    molecularWeight: 78.11,
    description: "Aromatic hydrocarbon with a hexagonal ring structure.",
    category: "organic",
    atoms: [
      { element: "C", position: [1.4, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0.7, 1.21, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.7, 1.21, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-1.4, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.7, -1.21, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0.7, -1.21, 0], color: "#909090", radius: 0.77 },
      { element: "H", position: [2.5, 0, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.25, 2.16, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.25, 2.16, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-2.5, 0, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.25, -2.16, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.25, -2.16, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 2, atom2: 3, order: 2 },
      { atom1: 3, atom2: 4, order: 1 },
      { atom1: 4, atom2: 5, order: 2 },
      { atom1: 5, atom2: 0, order: 1 },
      { atom1: 0, atom2: 6, order: 1 },
      { atom1: 1, atom2: 7, order: 1 },
      { atom1: 2, atom2: 8, order: 1 },
      { atom1: 3, atom2: 9, order: 1 },
      { atom1: 4, atom2: 10, order: 1 },
      { atom1: 5, atom2: 11, order: 1 },
    ],
    properties: {
      meltingPoint: "5.5°C",
      boilingPoint: "80.1°C",
      density: "0.879 g/cm³",
      polarity: "nonpolar",
      uses: ["Solvent", "Chemical synthesis", "Gasoline additive"],
    },
  },
  {
    id: "glucose",
    name: "Glucose",
    formula: "C₆H₁₂O₆",
    molecularWeight: 180.16,
    description: "Simple sugar and primary energy source for cells.",
    category: "biological",
    atoms: [
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.5, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [2.2, 1.3, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.5, 2.6, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0, 2.6, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [-0.7, 1.3, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "C", position: [-0.7, 3.9, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [-0.7, -1.0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [2.2, -1.0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [3.5, 1.3, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [2.2, 3.7, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-2.0, 3.9, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [0, 0, 1.1], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.5, 0, -1.1], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [2.2, 1.3, 1.1], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.5, 2.6, -1.1], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [0, 2.6, 1.1], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-0.7, 4.5, 0.9], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-0.7, 4.5, -0.9], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 2, atom2: 3, order: 1 },
      { atom1: 3, atom2: 4, order: 1 },
      { atom1: 4, atom2: 5, order: 1 },
      { atom1: 5, atom2: 0, order: 1 },
      { atom1: 4, atom2: 6, order: 1 },
      { atom1: 0, atom2: 7, order: 1 },
      { atom1: 1, atom2: 8, order: 1 },
      { atom1: 2, atom2: 9, order: 1 },
      { atom1: 3, atom2: 10, order: 1 },
      { atom1: 6, atom2: 11, order: 1 },
    ],
    properties: {
      meltingPoint: "146°C",
      density: "1.54 g/cm³",
      polarity: "polar",
      uses: ["Energy source", "Food sweetener", "Medical IV fluids"],
    },
  },
  // ============ GASES ============
  {
    id: "oxygen",
    name: "Oxygen",
    formula: "O₂",
    molecularWeight: 32.0,
    description: "Essential for respiration, makes up 21% of Earth's atmosphere.",
    category: "gas",
    atoms: [
      { element: "O", position: [-0.6, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [0.6, 0, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [{ atom1: 0, atom2: 1, order: 2 }],
    properties: {
      meltingPoint: "-218.8°C",
      boilingPoint: "-183°C",
      density: "1.43 g/L",
      polarity: "nonpolar",
      uses: ["Respiration", "Combustion", "Medical use", "Steel production"],
    },
  },
  {
    id: "nitrogen",
    name: "Nitrogen",
    formula: "N₂",
    molecularWeight: 28.01,
    description: "Makes up 78% of Earth's atmosphere. Triple bond makes it very stable.",
    category: "gas",
    atoms: [
      { element: "N", position: [-0.55, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "N", position: [0.55, 0, 0], color: "#3050F8", radius: 0.71 },
    ],
    bonds: [{ atom1: 0, atom2: 1, order: 3 }],
    properties: {
      meltingPoint: "-210°C",
      boilingPoint: "-196°C",
      density: "1.25 g/L",
      polarity: "nonpolar",
      uses: ["Fertilizers", "Cryogenics", "Food preservation", "Inert atmosphere"],
    },
  },
  {
    id: "hydrogen",
    name: "Hydrogen",
    formula: "H₂",
    molecularWeight: 2.016,
    description: "Lightest element, potential clean fuel source.",
    category: "gas",
    atoms: [
      { element: "H", position: [-0.37, 0, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [0.37, 0, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [{ atom1: 0, atom2: 1, order: 1 }],
    properties: {
      meltingPoint: "-259.2°C",
      boilingPoint: "-252.9°C",
      density: "0.09 g/L",
      polarity: "nonpolar",
      uses: ["Fuel cells", "Ammonia production", "Rocket fuel", "Hydrogenation"],
    },
  },
  {
    id: "ozone",
    name: "Ozone",
    formula: "O₃",
    molecularWeight: 48.0,
    description: "Protects Earth from UV radiation in the stratosphere.",
    category: "gas",
    atoms: [
      { element: "O", position: [0, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [1.1, 0.6, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-1.1, 0.6, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 0, atom2: 2, order: 1 },
    ],
    properties: {
      meltingPoint: "-192.2°C",
      boilingPoint: "-112°C",
      density: "2.14 g/L",
      polarity: "polar",
      uses: ["UV protection", "Water purification", "Sterilization"],
    },
  },
  {
    id: "helium",
    name: "Helium",
    formula: "He",
    molecularWeight: 4.003,
    description: "Noble gas, second lightest element. Used in balloons and cryogenics.",
    category: "gas",
    atoms: [{ element: "He", position: [0, 0, 0], color: "#D9FFFF", radius: 0.28 }],
    bonds: [],
    properties: {
      meltingPoint: "-272.2°C",
      boilingPoint: "-268.9°C",
      density: "0.18 g/L",
      polarity: "nonpolar",
      uses: ["Balloons", "MRI machines", "Cryogenics", "Welding"],
    },
  },
  {
    id: "neon",
    name: "Neon",
    formula: "Ne",
    molecularWeight: 20.18,
    description: "Noble gas known for its use in neon signs.",
    category: "gas",
    atoms: [{ element: "Ne", position: [0, 0, 0], color: "#B3E3F5", radius: 0.38 }],
    bonds: [],
    properties: {
      meltingPoint: "-248.6°C",
      boilingPoint: "-246.1°C",
      density: "0.90 g/L",
      polarity: "nonpolar",
      uses: ["Neon signs", "Lasers", "Cryogenics"],
    },
  },
  {
    id: "argon",
    name: "Argon",
    formula: "Ar",
    molecularWeight: 39.95,
    description: "Third most abundant gas in atmosphere. Used as inert atmosphere.",
    category: "gas",
    atoms: [{ element: "Ar", position: [0, 0, 0], color: "#80D1E3", radius: 0.71 }],
    bonds: [],
    properties: {
      meltingPoint: "-189.3°C",
      boilingPoint: "-185.8°C",
      density: "1.78 g/L",
      polarity: "nonpolar",
      uses: ["Welding", "Light bulbs", "Preserving wine", "3D printing"],
    },
  },
  {
    id: "carbon-monoxide",
    name: "Carbon Monoxide",
    formula: "CO",
    molecularWeight: 28.01,
    description: "Colorless, odorless toxic gas from incomplete combustion.",
    category: "gas",
    atoms: [
      { element: "C", position: [-0.56, 0, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [0.56, 0, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [{ atom1: 0, atom2: 1, order: 3 }],
    properties: {
      meltingPoint: "-205°C",
      boilingPoint: "-191.5°C",
      density: "1.14 g/L",
      polarity: "polar",
      uses: ["Metal production", "Chemical synthesis", "Fuel gas"],
    },
  },
  {
    id: "nitrogen-dioxide",
    name: "Nitrogen Dioxide",
    formula: "NO₂",
    molecularWeight: 46.01,
    description: "Reddish-brown toxic gas, contributes to smog.",
    category: "gas",
    atoms: [
      { element: "N", position: [0, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "O", position: [1.0, 0.6, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-1.0, 0.6, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 0, atom2: 2, order: 1 },
    ],
    properties: {
      meltingPoint: "-11.2°C",
      boilingPoint: "21.2°C",
      density: "1.88 g/L",
      polarity: "polar",
      uses: ["Chemical intermediate", "Rocket fuel oxidizer"],
    },
  },
  {
    id: "sulfur-dioxide",
    name: "Sulfur Dioxide",
    formula: "SO₂",
    molecularWeight: 64.07,
    description: "Pungent gas from volcanic activity and industrial processes.",
    category: "gas",
    atoms: [
      { element: "S", position: [0, 0, 0], color: "#FFFF30", radius: 1.05 },
      { element: "O", position: [1.2, 0.6, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-1.2, 0.6, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 0, atom2: 2, order: 2 },
    ],
    properties: {
      meltingPoint: "-72°C",
      boilingPoint: "-10°C",
      density: "2.63 g/L",
      polarity: "polar",
      uses: ["Food preservative", "Wine making", "Bleaching"],
    },
  },
  // ============ METALS AND METALLIC COMPOUNDS ============
  {
    id: "iron-oxide",
    name: "Iron(III) Oxide (Rust)",
    formula: "Fe₂O₃",
    molecularWeight: 159.69,
    description: "Common rust, red-brown color. Important iron ore.",
    category: "metal",
    atoms: [
      { element: "Fe", position: [-1.0, 0, 0], color: "#E06633", radius: 1.26 },
      { element: "Fe", position: [1.0, 0, 0], color: "#E06633", radius: 1.26 },
      { element: "O", position: [0, 1.0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-1.5, -1.0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [1.5, -1.0, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 1, atom2: 4, order: 1 },
    ],
    properties: {
      meltingPoint: "1566°C",
      density: "5.24 g/cm³",
      uses: ["Iron ore", "Pigment", "Polishing compound", "Magnetic storage"],
    },
  },
  {
    id: "copper-sulfate",
    name: "Copper Sulfate",
    formula: "CuSO₄",
    molecularWeight: 159.61,
    description: "Blue crystalline compound used in agriculture and chemistry.",
    category: "metal",
    atoms: [
      { element: "Cu", position: [0, 0, 2], color: "#C88033", radius: 1.28 },
      { element: "S", position: [0, 0, 0], color: "#FFFF30", radius: 1.05 },
      { element: "O", position: [1.2, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-1.2, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [0, 1.2, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [0, -1.2, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 1, atom2: 2, order: 2 },
      { atom1: 1, atom2: 3, order: 2 },
      { atom1: 1, atom2: 4, order: 1 },
      { atom1: 1, atom2: 5, order: 1 },
      { atom1: 0, atom2: 4, order: 1 },
    ],
    properties: {
      meltingPoint: "110°C (decomposes)",
      density: "3.6 g/cm³",
      polarity: "polar",
      uses: ["Fungicide", "Electroplating", "Analytical chemistry", "Art"],
    },
  },
  {
    id: "silver-nitrate",
    name: "Silver Nitrate",
    formula: "AgNO₃",
    molecularWeight: 169.87,
    description: "Light-sensitive compound used in photography and medicine.",
    category: "metal",
    atoms: [
      { element: "Ag", position: [0, 0, 1.5], color: "#C0C0C0", radius: 1.44 },
      { element: "N", position: [0, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "O", position: [1.1, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-0.55, 0.95, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-0.55, -0.95, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 1, atom2: 2, order: 2 },
      { atom1: 1, atom2: 3, order: 2 },
      { atom1: 1, atom2: 4, order: 1 },
      { atom1: 0, atom2: 4, order: 1 },
    ],
    properties: {
      meltingPoint: "212°C",
      density: "4.35 g/cm³",
      polarity: "polar",
      uses: ["Photography", "Cauterization", "Mirrors", "Analytical chemistry"],
    },
  },
  {
    id: "gold-chloride",
    name: "Gold(III) Chloride",
    formula: "AuCl₃",
    molecularWeight: 303.33,
    description: "Red crystalline compound used in gold plating.",
    category: "metal",
    atoms: [
      { element: "Au", position: [0, 0, 0], color: "#FFD123", radius: 1.44 },
      { element: "Cl", position: [1.8, 0, 0], color: "#1FF01F", radius: 0.99 },
      { element: "Cl", position: [-0.9, 1.56, 0], color: "#1FF01F", radius: 0.99 },
      { element: "Cl", position: [-0.9, -1.56, 0], color: "#1FF01F", radius: 0.99 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
    ],
    properties: {
      meltingPoint: "254°C",
      density: "3.9 g/cm³",
      uses: ["Gold plating", "Catalyst", "Photography"],
    },
  },
  {
    id: "titanium-dioxide",
    name: "Titanium Dioxide",
    formula: "TiO₂",
    molecularWeight: 79.87,
    description: "White pigment used in paints, sunscreen, and food.",
    category: "metal",
    atoms: [
      { element: "Ti", position: [0, 0, 0], color: "#BFC2C7", radius: 1.47 },
      { element: "O", position: [1.3, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-1.3, 0, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 0, atom2: 2, order: 2 },
    ],
    properties: {
      meltingPoint: "1843°C",
      density: "4.23 g/cm³",
      uses: ["White pigment", "Sunscreen", "Food coloring", "Photocatalyst"],
    },
  },
  {
    id: "zinc-oxide",
    name: "Zinc Oxide",
    formula: "ZnO",
    molecularWeight: 81.38,
    description: "White powder used in sunscreen, rubber, and medicine.",
    category: "metal",
    atoms: [
      { element: "Zn", position: [-0.9, 0, 0], color: "#7D80B0", radius: 1.22 },
      { element: "O", position: [0.9, 0, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [{ atom1: 0, atom2: 1, order: 2 }],
    properties: {
      meltingPoint: "1975°C",
      density: "5.61 g/cm³",
      uses: ["Sunscreen", "Rubber additive", "Medicine", "Ceramics"],
    },
  },
  {
    id: "potassium-permanganate",
    name: "Potassium Permanganate",
    formula: "KMnO₄",
    molecularWeight: 158.03,
    description: "Purple crystalline oxidizer used in water treatment.",
    category: "metal",
    atoms: [
      { element: "K", position: [0, 0, 2.5], color: "#8F40D4", radius: 2.27 },
      { element: "Mn", position: [0, 0, 0], color: "#9C7AC7", radius: 1.35 },
      { element: "O", position: [1.3, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-1.3, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [0, 1.3, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [0, -1.3, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 1, atom2: 2, order: 2 },
      { atom1: 1, atom2: 3, order: 2 },
      { atom1: 1, atom2: 4, order: 2 },
      { atom1: 1, atom2: 5, order: 1 },
    ],
    properties: {
      meltingPoint: "240°C (decomposes)",
      density: "2.7 g/cm³",
      uses: ["Water treatment", "Disinfectant", "Analytical chemistry"],
    },
  },
  {
    id: "aluminum-oxide",
    name: "Aluminum Oxide (Alumina)",
    formula: "Al₂O₃",
    molecularWeight: 101.96,
    description: "Very hard material used as abrasive and in ceramics.",
    category: "metal",
    atoms: [
      { element: "Al", position: [-1.0, 0, 0], color: "#BFA6A6", radius: 1.21 },
      { element: "Al", position: [1.0, 0, 0], color: "#BFA6A6", radius: 1.21 },
      { element: "O", position: [0, 1.0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-1.5, -1.0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [1.5, -1.0, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 1, atom2: 4, order: 1 },
    ],
    properties: {
      meltingPoint: "2072°C",
      density: "3.95 g/cm³",
      uses: ["Abrasive", "Ceramics", "Insulator", "Catalyst support"],
    },
  },
  {
    id: "mercury-oxide",
    name: "Mercury(II) Oxide",
    formula: "HgO",
    molecularWeight: 216.59,
    description: "Red or yellow powder, historically used in chemistry.",
    category: "metal",
    atoms: [
      { element: "Hg", position: [-1.0, 0, 0], color: "#B8B8D0", radius: 1.51 },
      { element: "O", position: [1.0, 0, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [{ atom1: 0, atom2: 1, order: 2 }],
    properties: {
      meltingPoint: "500°C (decomposes)",
      density: "11.1 g/cm³",
      uses: ["Historical oxygen production", "Pigment", "Catalyst"],
    },
  },
  {
    id: "lead-oxide",
    name: "Lead(II) Oxide",
    formula: "PbO",
    molecularWeight: 223.2,
    description: "Yellow to red powder used in glass and ceramics.",
    category: "metal",
    atoms: [
      { element: "Pb", position: [-1.1, 0, 0], color: "#575961", radius: 1.75 },
      { element: "O", position: [1.1, 0, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [{ atom1: 0, atom2: 1, order: 2 }],
    properties: {
      meltingPoint: "888°C",
      density: "9.53 g/cm³",
      uses: ["Glass making", "Ceramics", "Lead-acid batteries"],
    },
  },
  // ============ PHARMACEUTICAL ============
  {
    id: "aspirin",
    name: "Aspirin",
    formula: "C₉H₈O₄",
    molecularWeight: 180.16,
    description: "Common pain reliever and anti-inflammatory drug.",
    category: "pharmaceutical",
    atoms: [
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.4, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [2.1, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.4, 2.4, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0, 2.4, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.7, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [-0.7, -1.0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "C", position: [-2.0, -1.0, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [-2.7, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "C", position: [-2.1, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [-2.8, 2.2, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-2.7, -2.0, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 2, atom2: 3, order: 2 },
      { atom1: 3, atom2: 4, order: 1 },
      { atom1: 4, atom2: 5, order: 2 },
      { atom1: 5, atom2: 0, order: 1 },
      { atom1: 0, atom2: 6, order: 1 },
      { atom1: 6, atom2: 7, order: 1 },
      { atom1: 7, atom2: 8, order: 2 },
      { atom1: 5, atom2: 9, order: 1 },
      { atom1: 9, atom2: 10, order: 2 },
      { atom1: 9, atom2: 11, order: 1 },
    ],
    properties: {
      meltingPoint: "136°C",
      density: "1.40 g/cm³",
      polarity: "polar",
      uses: ["Pain relief", "Fever reduction", "Anti-inflammatory", "Blood thinner"],
    },
  },
  {
    id: "caffeine",
    name: "Caffeine",
    formula: "C₈H₁₀N₄O₂",
    molecularWeight: 194.19,
    description: "Stimulant found in coffee, tea, and energy drinks.",
    category: "pharmaceutical",
    atoms: [
      { element: "N", position: [0, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.2, 0.5, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [1.8, 1.7, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.0, 2.8, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.4, 2.5, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.8, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [-2.1, 0.9, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [-2.5, -0.4, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [-1.5, -1.2, 0], color: "#3050F8", radius: 0.71 },
      { element: "O", position: [2.0, -0.5, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [1.5, 3.9, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 2, atom2: 3, order: 1 },
      { atom1: 3, atom2: 4, order: 1 },
      { atom1: 4, atom2: 5, order: 2 },
      { atom1: 5, atom2: 0, order: 1 },
      { atom1: 5, atom2: 6, order: 1 },
      { atom1: 6, atom2: 7, order: 1 },
      { atom1: 7, atom2: 8, order: 2 },
      { atom1: 8, atom2: 0, order: 1 },
      { atom1: 1, atom2: 9, order: 2 },
      { atom1: 3, atom2: 10, order: 2 },
    ],
    properties: {
      meltingPoint: "235°C",
      density: "1.23 g/cm³",
      polarity: "polar",
      uses: ["Stimulant", "Pain relief enhancer", "Energy drinks"],
    },
  },
  {
    id: "ibuprofen",
    name: "Ibuprofen",
    formula: "C₁₃H₁₈O₂",
    molecularWeight: 206.29,
    description: "Non-steroidal anti-inflammatory drug (NSAID).",
    category: "pharmaceutical",
    atoms: [
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.4, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [2.1, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.4, 2.4, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0, 2.4, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.7, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [2.1, -1.2, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [3.6, -1.2, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [4.3, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.7, 3.6, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-2.2, 3.6, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [-2.9, 2.5, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-2.9, 4.7, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 2, atom2: 3, order: 2 },
      { atom1: 3, atom2: 4, order: 1 },
      { atom1: 4, atom2: 5, order: 2 },
      { atom1: 5, atom2: 0, order: 1 },
      { atom1: 1, atom2: 6, order: 1 },
      { atom1: 6, atom2: 7, order: 1 },
      { atom1: 7, atom2: 8, order: 1 },
      { atom1: 4, atom2: 9, order: 1 },
      { atom1: 9, atom2: 10, order: 1 },
      { atom1: 10, atom2: 11, order: 2 },
      { atom1: 10, atom2: 12, order: 1 },
    ],
    properties: {
      meltingPoint: "76°C",
      density: "1.03 g/cm³",
      polarity: "polar",
      uses: ["Pain relief", "Fever reduction", "Anti-inflammatory"],
    },
  },
  {
    id: "paracetamol",
    name: "Paracetamol (Acetaminophen)",
    formula: "C₈H₉NO₂",
    molecularWeight: 151.16,
    description: "Common pain reliever and fever reducer.",
    category: "pharmaceutical",
    atoms: [
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.4, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [2.1, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.4, 2.4, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0, 2.4, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.7, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [2.1, 3.6, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "N", position: [-2.1, 1.2, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [-2.8, 0, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [-2.1, -1.0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "C", position: [-4.3, 0, 0], color: "#909090", radius: 0.77 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 2, atom2: 3, order: 2 },
      { atom1: 3, atom2: 4, order: 1 },
      { atom1: 4, atom2: 5, order: 2 },
      { atom1: 5, atom2: 0, order: 1 },
      { atom1: 3, atom2: 6, order: 1 },
      { atom1: 5, atom2: 7, order: 1 },
      { atom1: 7, atom2: 8, order: 1 },
      { atom1: 8, atom2: 9, order: 2 },
      { atom1: 8, atom2: 10, order: 1 },
    ],
    properties: {
      meltingPoint: "169°C",
      density: "1.26 g/cm³",
      polarity: "polar",
      uses: ["Pain relief", "Fever reduction"],
    },
  },
  // ============ BIOLOGICAL ============
  {
    id: "adenine",
    name: "Adenine",
    formula: "C₅H₅N₅",
    molecularWeight: 135.13,
    description: "DNA/RNA nucleobase, pairs with thymine (DNA) or uracil (RNA).",
    category: "biological",
    atoms: [
      { element: "N", position: [0, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.2, 0.5, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [1.8, 1.7, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.0, 2.8, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.4, 2.5, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.8, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [-2.0, 0.8, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [-2.3, -0.5, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [-1.3, -1.2, 0], color: "#3050F8", radius: 0.71 },
      { element: "N", position: [1.5, 4.0, 0], color: "#3050F8", radius: 0.71 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 2 },
      { atom1: 2, atom2: 3, order: 1 },
      { atom1: 3, atom2: 4, order: 2 },
      { atom1: 4, atom2: 5, order: 1 },
      { atom1: 5, atom2: 0, order: 2 },
      { atom1: 5, atom2: 6, order: 1 },
      { atom1: 6, atom2: 7, order: 2 },
      { atom1: 7, atom2: 8, order: 1 },
      { atom1: 8, atom2: 0, order: 1 },
      { atom1: 3, atom2: 9, order: 1 },
    ],
    properties: {
      meltingPoint: "360-365°C",
      density: "1.6 g/cm³",
      polarity: "polar",
      uses: ["DNA/RNA component", "ATP energy transfer", "Genetic coding"],
    },
  },
  {
    id: "thymine",
    name: "Thymine",
    formula: "C₅H₆N₂O₂",
    molecularWeight: 126.11,
    description: "DNA nucleobase that pairs with adenine.",
    category: "biological",
    atoms: [
      { element: "N", position: [0, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.2, 0.5, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [1.8, 1.7, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.0, 2.8, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.4, 2.5, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.8, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [2.0, -0.3, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [1.5, 3.9, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "C", position: [-1.2, 3.7, 0], color: "#909090", radius: 0.77 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 2, atom2: 3, order: 1 },
      { atom1: 3, atom2: 4, order: 1 },
      { atom1: 4, atom2: 5, order: 2 },
      { atom1: 5, atom2: 0, order: 1 },
      { atom1: 1, atom2: 6, order: 2 },
      { atom1: 3, atom2: 7, order: 2 },
      { atom1: 4, atom2: 8, order: 1 },
    ],
    properties: {
      meltingPoint: "316-317°C",
      density: "1.23 g/cm³",
      polarity: "polar",
      uses: ["DNA component", "Genetic coding"],
    },
  },
  {
    id: "cytosine",
    name: "Cytosine",
    formula: "C₄H₅N₃O",
    molecularWeight: 111.1,
    description: "DNA/RNA nucleobase that pairs with guanine.",
    category: "biological",
    atoms: [
      { element: "N", position: [0, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.2, 0.5, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [1.8, 1.7, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.0, 2.8, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.4, 2.5, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.8, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [2.0, -0.3, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "N", position: [1.5, 3.9, 0], color: "#3050F8", radius: 0.71 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 2, atom2: 3, order: 2 },
      { atom1: 3, atom2: 4, order: 1 },
      { atom1: 4, atom2: 5, order: 2 },
      { atom1: 5, atom2: 0, order: 1 },
      { atom1: 1, atom2: 6, order: 2 },
      { atom1: 3, atom2: 7, order: 1 },
    ],
    properties: {
      meltingPoint: "320-325°C",
      density: "1.55 g/cm³",
      polarity: "polar",
      uses: ["DNA/RNA component", "Genetic coding"],
    },
  },
  {
    id: "guanine",
    name: "Guanine",
    formula: "C₅H₅N₅O",
    molecularWeight: 151.13,
    description: "DNA/RNA nucleobase that pairs with cytosine.",
    category: "biological",
    atoms: [
      { element: "N", position: [0, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.2, 0.5, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [1.8, 1.7, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.0, 2.8, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.4, 2.5, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.8, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [-2.0, 0.8, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [-2.3, -0.5, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [-1.3, -1.2, 0], color: "#3050F8", radius: 0.71 },
      { element: "O", position: [1.5, 4.0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "N", position: [-1.0, 3.6, 0], color: "#3050F8", radius: 0.71 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 2 },
      { atom1: 2, atom2: 3, order: 1 },
      { atom1: 3, atom2: 4, order: 1 },
      { atom1: 4, atom2: 5, order: 2 },
      { atom1: 5, atom2: 0, order: 1 },
      { atom1: 5, atom2: 6, order: 1 },
      { atom1: 6, atom2: 7, order: 2 },
      { atom1: 7, atom2: 8, order: 1 },
      { atom1: 8, atom2: 0, order: 1 },
      { atom1: 3, atom2: 9, order: 2 },
      { atom1: 4, atom2: 10, order: 1 },
    ],
    properties: {
      meltingPoint: "360°C (decomp)",
      density: "2.2 g/cm³",
      polarity: "polar",
      uses: ["DNA/RNA component", "Genetic coding", "GTP energy"],
    },
  },
  {
    id: "uracil",
    name: "Uracil",
    formula: "C₄H₄N₂O₂",
    molecularWeight: 112.09,
    description: "RNA nucleobase that replaces thymine, pairs with adenine.",
    category: "biological",
    atoms: [
      { element: "N", position: [0, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.2, 0.5, 0], color: "#909090", radius: 0.77 },
      { element: "N", position: [1.8, 1.7, 0], color: "#3050F8", radius: 0.71 },
      { element: "C", position: [1.0, 2.8, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.4, 2.5, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [-0.8, 1.2, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [2.0, -0.3, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [1.5, 3.9, 0], color: "#FF0D0D", radius: 0.66 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 2, atom2: 3, order: 1 },
      { atom1: 3, atom2: 4, order: 2 },
      { atom1: 4, atom2: 5, order: 1 },
      { atom1: 5, atom2: 0, order: 1 },
      { atom1: 1, atom2: 6, order: 2 },
      { atom1: 3, atom2: 7, order: 2 },
    ],
    properties: {
      meltingPoint: "335°C",
      density: "1.32 g/cm³",
      polarity: "polar",
      uses: ["RNA component", "Genetic coding"],
    },
  },
  // ============ POLYMERS ============
  {
    id: "polyethylene-unit",
    name: "Polyethylene (Monomer)",
    formula: "(C₂H₄)ₙ",
    molecularWeight: 28.05,
    description: "Most common plastic, made from ethylene monomers.",
    category: "polymer",
    atoms: [
      { element: "C", position: [-0.77, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0.77, 0, 0], color: "#909090", radius: 0.77 },
      { element: "H", position: [-1.17, 0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.17, -0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.17, 0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.17, -0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 1, atom2: 4, order: 1 },
      { atom1: 1, atom2: 5, order: 1 },
    ],
    properties: {
      meltingPoint: "105-115°C",
      density: "0.92-0.97 g/cm³",
      polarity: "nonpolar",
      uses: ["Plastic bags", "Bottles", "Pipes", "Packaging"],
    },
  },
  {
    id: "pvc-unit",
    name: "PVC (Monomer)",
    formula: "(C₂H₃Cl)ₙ",
    molecularWeight: 62.5,
    description: "Polyvinyl chloride - widely used plastic for pipes and cables.",
    category: "polymer",
    atoms: [
      { element: "C", position: [-0.77, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0.77, 0, 0], color: "#909090", radius: 0.77 },
      { element: "H", position: [-1.17, 0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.17, -0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.17, 0.63, 0.63], color: "#FFFFFF", radius: 0.31 },
      { element: "Cl", position: [1.17, -1.0, 0], color: "#1FF01F", radius: 0.99 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 1, atom2: 4, order: 1 },
      { atom1: 1, atom2: 5, order: 1 },
    ],
    properties: {
      meltingPoint: "100-260°C",
      density: "1.3-1.45 g/cm³",
      polarity: "polar",
      uses: ["Pipes", "Window frames", "Cables", "Flooring"],
    },
  },
  {
    id: "polystyrene-unit",
    name: "Polystyrene (Monomer)",
    formula: "(C₈H₈)ₙ",
    molecularWeight: 104.15,
    description: "Versatile plastic used in packaging and insulation (Styrofoam).",
    category: "polymer",
    atoms: [
      { element: "C", position: [-0.77, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0.77, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.5, 1.4, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [2.9, 1.4, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [3.6, 2.6, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [2.9, 3.8, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [1.5, 3.8, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0.8, 2.6, 0], color: "#909090", radius: 0.77 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 1 },
      { atom1: 2, atom2: 3, order: 2 },
      { atom1: 3, atom2: 4, order: 1 },
      { atom1: 4, atom2: 5, order: 2 },
      { atom1: 5, atom2: 6, order: 1 },
      { atom1: 6, atom2: 7, order: 2 },
      { atom1: 7, atom2: 2, order: 1 },
    ],
    properties: {
      meltingPoint: "240°C",
      density: "1.04-1.09 g/cm³",
      polarity: "nonpolar",
      uses: ["Packaging", "Insulation", "Disposable cups", "CD cases"],
    },
  },
  // ============ INDUSTRIAL ============
  {
    id: "nitric-acid",
    name: "Nitric Acid",
    formula: "HNO₃",
    molecularWeight: 63.01,
    description: "Strong acid used in fertilizers and explosives.",
    category: "industrial",
    atoms: [
      { element: "N", position: [0, 0, 0], color: "#3050F8", radius: 0.71 },
      { element: "O", position: [1.1, 0.5, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-0.5, 1.1, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-0.6, -1.0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [-1.4, -1.3, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 0, atom2: 2, order: 2 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 3, atom2: 4, order: 1 },
    ],
    properties: {
      meltingPoint: "-42°C",
      boilingPoint: "83°C",
      density: "1.51 g/cm³",
      polarity: "polar",
      uses: ["Fertilizers", "Explosives", "Etching", "Rocket fuel"],
    },
  },
  {
    id: "phosphoric-acid",
    name: "Phosphoric Acid",
    formula: "H₃PO₄",
    molecularWeight: 98.0,
    description: "Weak acid used in fertilizers and soft drinks.",
    category: "industrial",
    atoms: [
      { element: "P", position: [0, 0, 0], color: "#FF8000", radius: 1.07 },
      { element: "O", position: [1.3, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-0.65, 1.12, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [-0.65, -1.12, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [0, 0, 1.5], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [2.2, 0, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.2, 1.8, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.2, -1.8, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 0, atom2: 4, order: 2 },
      { atom1: 1, atom2: 5, order: 1 },
      { atom1: 2, atom2: 6, order: 1 },
      { atom1: 3, atom2: 7, order: 1 },
    ],
    properties: {
      meltingPoint: "42.4°C",
      boilingPoint: "158°C",
      density: "1.88 g/cm³",
      polarity: "polar",
      uses: ["Fertilizers", "Soft drinks", "Rust removal", "Food additive"],
    },
  },
  {
    id: "hydrogen-peroxide",
    name: "Hydrogen Peroxide",
    formula: "H₂O₂",
    molecularWeight: 34.01,
    description: "Powerful oxidizer used as disinfectant and bleaching agent.",
    category: "industrial",
    atoms: [
      { element: "O", position: [-0.7, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [0.7, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [-1.1, 0.9, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.1, -0.9, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 1, atom2: 3, order: 1 },
    ],
    properties: {
      meltingPoint: "-0.43°C",
      boilingPoint: "150.2°C",
      density: "1.45 g/cm³",
      polarity: "polar",
      uses: ["Disinfectant", "Bleaching", "Rocket propellant", "Hair bleach"],
    },
  },
  // Additional molecules for 100+ total
  {
    id: "formaldehyde",
    name: "Formaldehyde",
    formula: "CH₂O",
    molecularWeight: 30.03,
    description: "Simplest aldehyde, used in preservation and resins.",
    category: "organic",
    atoms: [
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [1.2, 0, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [-0.5, 0.9, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-0.5, -0.9, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
    ],
    properties: {
      meltingPoint: "-92°C",
      boilingPoint: "-19°C",
      density: "0.82 g/cm³",
      polarity: "polar",
      uses: ["Preservation", "Resins", "Disinfectant"],
    },
  },
  {
    id: "acetic-acid",
    name: "Acetic Acid (Vinegar)",
    formula: "CH₃COOH",
    molecularWeight: 60.05,
    description: "Main component of vinegar, weak organic acid.",
    category: "organic",
    atoms: [
      { element: "C", position: [-0.77, 0, 0], color: "#909090", radius: 0.77 },
      { element: "C", position: [0.77, 0, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [1.4, 1.1, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [1.4, -1.1, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [-1.17, 0.6, 0.6], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.17, -0.6, 0.6], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.17, 0, -0.85], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [2.3, -1.1, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 1, atom2: 2, order: 2 },
      { atom1: 1, atom2: 3, order: 1 },
      { atom1: 0, atom2: 4, order: 1 },
      { atom1: 0, atom2: 5, order: 1 },
      { atom1: 0, atom2: 6, order: 1 },
      { atom1: 3, atom2: 7, order: 1 },
    ],
    properties: {
      meltingPoint: "16.6°C",
      boilingPoint: "118°C",
      density: "1.05 g/cm³",
      polarity: "polar",
      uses: ["Vinegar", "Food preservation", "Solvent", "Chemical synthesis"],
    },
  },
  {
    id: "formic-acid",
    name: "Formic Acid",
    formula: "HCOOH",
    molecularWeight: 46.03,
    description: "Simplest carboxylic acid, found in ant venom.",
    category: "organic",
    atoms: [
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [1.1, 0.6, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "O", position: [0.6, -1.1, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "H", position: [-1.0, 0, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.4, -1.4, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 2, atom2: 4, order: 1 },
    ],
    properties: {
      meltingPoint: "8.4°C",
      boilingPoint: "100.8°C",
      density: "1.22 g/cm³",
      polarity: "polar",
      uses: ["Preservative", "Antibacterial", "Leather tanning"],
    },
  },
  {
    id: "urea",
    name: "Urea",
    formula: "CO(NH₂)₂",
    molecularWeight: 60.06,
    description: "Organic compound in urine, major nitrogen fertilizer.",
    category: "biological",
    atoms: [
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "O", position: [0, 1.2, 0], color: "#FF0D0D", radius: 0.66 },
      { element: "N", position: [1.1, -0.6, 0], color: "#3050F8", radius: 0.71 },
      { element: "N", position: [-1.1, -0.6, 0], color: "#3050F8", radius: 0.71 },
      { element: "H", position: [1.8, 0, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [1.3, -1.5, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.8, 0, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "H", position: [-1.3, -1.5, 0], color: "#FFFFFF", radius: 0.31 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 2 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 2, atom2: 4, order: 1 },
      { atom1: 2, atom2: 5, order: 1 },
      { atom1: 3, atom2: 6, order: 1 },
      { atom1: 3, atom2: 7, order: 1 },
    ],
    properties: {
      meltingPoint: "133°C",
      density: "1.32 g/cm³",
      polarity: "polar",
      uses: ["Fertilizer", "Animal feed", "Skincare", "Chemical synthesis"],
    },
  },
  {
    id: "chloroform",
    name: "Chloroform",
    formula: "CHCl₃",
    molecularWeight: 119.38,
    description: "Organic solvent, formerly used as anesthetic.",
    category: "organic",
    atoms: [
      { element: "C", position: [0, 0, 0], color: "#909090", radius: 0.77 },
      { element: "H", position: [0, 1.1, 0], color: "#FFFFFF", radius: 0.31 },
      { element: "Cl", position: [1.5, -0.5, 0], color: "#1FF01F", radius: 0.99 },
      { element: "Cl", position: [-0.75, -0.5, 1.3], color: "#1FF01F", radius: 0.99 },
      { element: "Cl", position: [-0.75, -0.5, -1.3], color: "#1FF01F", radius: 0.99 },
    ],
    bonds: [
      { atom1: 0, atom2: 1, order: 1 },
      { atom1: 0, atom2: 2, order: 1 },
      { atom1: 0, atom2: 3, order: 1 },
      { atom1: 0, atom2: 4, order: 1 },
    ],
    properties: {
      meltingPoint: "-63.5°C",
      boilingPoint: "61.2°C",
      density: "1.49 g/cm³",
      polarity: "polar",
      uses: ["Solvent", "Refrigerant precursor", "Chemical synthesis"],
    },
  },
]
