// Complete data for Animal and Plant cell organelles

export interface Organelle {
  id: string
  name: string
  description: string
  function: string
  size: string
  color: string
  position: [number, number, number]
  scale: [number, number, number]
  shape: "sphere" | "ellipsoid" | "cylinder" | "torus" | "irregular" | "membrane" | "box"
  details: string[]
  funFact: string
  foundIn: "both" | "animal" | "plant"
}

export const organelles: Organelle[] = [
  // Nucleus
  {
    id: "nucleus",
    name: "Nucleus",
    description: "The control center of the cell containing genetic material (DNA)",
    function: "Controls cell activities and contains genetic information",
    size: "5-10 μm diameter",
    color: "#8B5CF6",
    position: [0, 0, 0],
    scale: [1.8, 1.8, 1.8],
    shape: "sphere",
    details: [
      "Contains chromosomes with DNA",
      "Surrounded by nuclear envelope with pores",
      "Contains nucleolus for ribosome production",
      "Controls gene expression and cell division",
    ],
    funFact: "If uncoiled, the DNA in one human cell would stretch about 2 meters!",
    foundIn: "both",
  },
  // Nucleolus
  {
    id: "nucleolus",
    name: "Nucleolus",
    description: "Dense region inside the nucleus where ribosomal RNA is made",
    function: "Produces ribosomal subunits",
    size: "1-3 μm diameter",
    color: "#7C3AED",
    position: [0.3, 0.3, 0],
    scale: [0.6, 0.6, 0.6],
    shape: "sphere",
    details: [
      "Not membrane-bound",
      "Assembles ribosomal RNA",
      "Can have multiple nucleoli per nucleus",
      "Disappears during cell division",
    ],
    funFact: "The nucleolus is the largest structure in the nucleus!",
    foundIn: "both",
  },
  // Mitochondria
  {
    id: "mitochondria",
    name: "Mitochondria",
    description: "The powerhouse of the cell that generates ATP energy",
    function: "Cellular respiration and ATP production",
    size: "1-10 μm length",
    color: "#EF4444",
    position: [2.5, 1, 0.5],
    scale: [0.8, 0.4, 0.4],
    shape: "ellipsoid",
    details: [
      "Has its own DNA (maternal inheritance)",
      "Double membrane structure",
      "Inner membrane has cristae folds",
      "Produces 36-38 ATP per glucose molecule",
    ],
    funFact: "Mitochondria were once free-living bacteria that became part of cells through endosymbiosis!",
    foundIn: "both",
  },
  // Mitochondria 2
  {
    id: "mitochondria2",
    name: "Mitochondria",
    description: "Additional mitochondrion for energy production",
    function: "Cellular respiration and ATP production",
    size: "1-10 μm length",
    color: "#DC2626",
    position: [-2, -1.5, 1],
    scale: [0.7, 0.35, 0.35],
    shape: "ellipsoid",
    details: [
      "Cells can have hundreds to thousands",
      "More abundant in active cells",
      "Can divide independently",
      "Essential for aerobic respiration",
    ],
    funFact: "Liver cells can have up to 2,000 mitochondria each!",
    foundIn: "both",
  },
  // Mitochondria 3
  {
    id: "mitochondria3",
    name: "Mitochondria",
    description: "Additional mitochondrion",
    function: "Cellular respiration and ATP production",
    size: "1-10 μm length",
    color: "#F87171",
    position: [1.5, -2, -0.5],
    scale: [0.6, 0.3, 0.3],
    shape: "ellipsoid",
    details: [
      "Generate most of cell's ATP",
      "Involved in cell signaling",
      "Play role in cell death (apoptosis)",
      "Have their own ribosomes",
    ],
    funFact: "Your body produces roughly your body weight in ATP every day!",
    foundIn: "both",
  },
  // Endoplasmic Reticulum (Rough)
  {
    id: "rough-er",
    name: "Rough Endoplasmic Reticulum",
    description: "Membrane network studded with ribosomes for protein synthesis",
    function: "Protein synthesis and transport",
    size: "Network throughout cell",
    color: "#3B82F6",
    position: [1.2, -0.5, -1],
    scale: [1.5, 0.8, 0.3],
    shape: "irregular",
    details: [
      "Covered with ribosomes (giving rough appearance)",
      "Continuous with nuclear envelope",
      "Folds and modifies proteins",
      "Produces membrane-bound proteins",
    ],
    funFact: "The ER membrane can make up more than half of the total membrane in a cell!",
    foundIn: "both",
  },
  // Endoplasmic Reticulum (Smooth)
  {
    id: "smooth-er",
    name: "Smooth Endoplasmic Reticulum",
    description: "Membrane network without ribosomes for lipid synthesis",
    function: "Lipid synthesis and detoxification",
    size: "Network throughout cell",
    color: "#60A5FA",
    position: [-1.5, 0.8, 1],
    scale: [1.2, 0.6, 0.3],
    shape: "irregular",
    details: [
      "No ribosomes attached",
      "Synthesizes lipids and steroids",
      "Detoxifies drugs and poisons",
      "Stores calcium ions",
    ],
    funFact: "Liver cells have abundant smooth ER to detoxify alcohol and drugs!",
    foundIn: "both",
  },
  // Golgi Apparatus
  {
    id: "golgi",
    name: "Golgi Apparatus",
    description: "Stack of flattened membranes that processes and packages proteins",
    function: "Modifies, sorts, and packages proteins for secretion",
    size: "1-3 μm",
    color: "#F59E0B",
    position: [-2.2, 0.3, -0.5],
    scale: [1, 0.6, 0.4],
    shape: "irregular",
    details: [
      "Stack of 4-8 flattened cisternae",
      "Has cis (receiving) and trans (shipping) faces",
      "Adds carbohydrates to proteins (glycosylation)",
      "Produces lysosomes",
    ],
    funFact: "Named after Italian scientist Camillo Golgi who discovered it in 1898!",
    foundIn: "both",
  },
  // Lysosomes (Animal only)
  {
    id: "lysosome1",
    name: "Lysosome",
    description: "Digestive organelle containing enzymes to break down materials",
    function: "Digests waste materials and cellular debris",
    size: "0.1-1.2 μm",
    color: "#84CC16",
    position: [2, -1.8, 0],
    scale: [0.35, 0.35, 0.35],
    shape: "sphere",
    details: [
      "Contains 50+ digestive enzymes",
      "pH of about 4.5-5 (acidic)",
      "Breaks down old organelles",
      "Defends against pathogens",
    ],
    funFact: 'Lysosomes are called "suicide bags" because they can destroy the cell if ruptured!',
    foundIn: "animal",
  },
  // Lysosome 2
  {
    id: "lysosome2",
    name: "Lysosome",
    description: "Additional lysosome for waste digestion",
    function: "Digests waste materials and cellular debris",
    size: "0.1-1.2 μm",
    color: "#A3E635",
    position: [-1, 2.2, 0.5],
    scale: [0.3, 0.3, 0.3],
    shape: "sphere",
    details: [
      "Formed by Golgi apparatus",
      "Fuses with food vacuoles",
      "Recycles cell components",
      "Important for autophagy",
    ],
    funFact: "White blood cells use lysosomes to destroy bacteria they engulf!",
    foundIn: "animal",
  },
  // Ribosomes
  {
    id: "ribosome1",
    name: "Ribosome",
    description: "Tiny organelle that synthesizes proteins from amino acids",
    function: "Protein synthesis (translation)",
    size: "20-30 nm",
    color: "#EC4899",
    position: [1.5, 0.2, -0.8],
    scale: [0.15, 0.15, 0.15],
    shape: "sphere",
    details: [
      "Made of RNA and protein",
      "Has large and small subunits",
      "Can be free or attached to ER",
      "Reads mRNA to make proteins",
    ],
    funFact: "A single cell can contain millions of ribosomes!",
    foundIn: "both",
  },
  // Multiple ribosomes
  {
    id: "ribosome2",
    name: "Ribosome",
    description: "Protein synthesis machinery",
    function: "Protein synthesis",
    size: "20-30 nm",
    color: "#F472B6",
    position: [1.8, 0.5, -0.6],
    scale: [0.12, 0.12, 0.12],
    shape: "sphere",
    details: ["Part of polyribosome chain", "Translates mRNA", "Universal in all cells", "Essential for life"],
    funFact: "Ribosomes work so fast they can add 20 amino acids per second!",
    foundIn: "both",
  },
  {
    id: "ribosome3",
    name: "Ribosome",
    description: "Protein synthesis machinery",
    function: "Protein synthesis",
    size: "20-30 nm",
    color: "#FB7185",
    position: [1.3, -0.1, -1.1],
    scale: [0.13, 0.13, 0.13],
    shape: "sphere",
    details: ["Free ribosome", "Makes cytoplasmic proteins", "Not attached to ER", "Floats in cytoplasm"],
    funFact: "Free ribosomes make proteins used inside the cell!",
    foundIn: "both",
  },
  // Centrioles (Animal only)
  {
    id: "centriole1",
    name: "Centriole",
    description: "Cylindrical structure that helps organize cell division",
    function: "Organizes spindle fibers during cell division",
    size: "0.2 μm diameter, 0.4 μm length",
    color: "#06B6D4",
    position: [2.8, 0, 0],
    scale: [0.25, 0.5, 0.25],
    shape: "cylinder",
    details: [
      "Made of 9 triplet microtubules",
      "Always found in pairs at right angles",
      "Forms centrosome with pericentriolar material",
      "Duplicates before cell division",
    ],
    funFact: "Plant cells divide without centrioles using other organizing centers!",
    foundIn: "animal",
  },
  {
    id: "centriole2",
    name: "Centriole",
    description: "Second centriole of the pair",
    function: "Organizes spindle fibers during cell division",
    size: "0.2 μm diameter, 0.4 μm length",
    color: "#22D3D1",
    position: [2.8, 0.3, 0.3],
    scale: [0.25, 0.5, 0.25],
    shape: "cylinder",
    details: [
      "Perpendicular to other centriole",
      "Part of centrosome",
      "Organizes microtubules",
      "Important for cilia/flagella formation",
    ],
    funFact: "Centrioles also help form cilia and flagella for cell movement!",
    foundIn: "animal",
  },
  // Vacuole (small in animal, large in plant)
  {
    id: "vacuole-animal",
    name: "Vacuole",
    description: "Small storage organelle for water and nutrients",
    function: "Stores water, nutrients, and waste products",
    size: "Variable (small in animal cells)",
    color: "#A78BFA",
    position: [-2.5, -1.5, 0],
    scale: [0.5, 0.5, 0.5],
    shape: "sphere",
    details: [
      "Multiple small vacuoles in animal cells",
      "Stores nutrients and water",
      "Can contain waste products",
      "Helps maintain cell pressure",
    ],
    funFact: "Animal cells have many small vacuoles, unlike plant cells with one large one!",
    foundIn: "animal",
  },
  // Central Vacuole (Plant only - very large)
  {
    id: "central-vacuole",
    name: "Central Vacuole",
    description: "Large water-filled organelle that maintains cell pressure",
    function: "Maintains turgor pressure, stores nutrients and waste",
    size: "Up to 90% of cell volume",
    color: "#C4B5FD",
    position: [0, 0, 0],
    scale: [3.5, 3.5, 3.5],
    shape: "sphere",
    details: [
      "Surrounded by tonoplast membrane",
      "Contains cell sap",
      "Maintains turgor pressure",
      "Stores pigments, nutrients, waste",
    ],
    funFact: "The central vacuole can occupy up to 90% of a plant cell's volume!",
    foundIn: "plant",
  },
  // Chloroplast (Plant only)
  {
    id: "chloroplast1",
    name: "Chloroplast",
    description: "Organelle that performs photosynthesis",
    function: "Converts sunlight into glucose (photosynthesis)",
    size: "3-10 μm",
    color: "#22C55E",
    position: [2.5, 2, 0],
    scale: [1, 0.5, 0.5],
    shape: "ellipsoid",
    details: [
      "Contains chlorophyll (green pigment)",
      "Has its own DNA",
      "Double membrane with thylakoids inside",
      "Produces oxygen as byproduct",
    ],
    funFact: "Chloroplasts were once free-living cyanobacteria, similar to mitochondria!",
    foundIn: "plant",
  },
  {
    id: "chloroplast2",
    name: "Chloroplast",
    description: "Additional chloroplast for photosynthesis",
    function: "Converts sunlight into glucose",
    size: "3-10 μm",
    color: "#4ADE80",
    position: [-2.8, 1.5, 0.5],
    scale: [0.9, 0.45, 0.45],
    shape: "ellipsoid",
    details: [
      "A leaf cell can have 10-100 chloroplasts",
      "Grana stacks contain thylakoids",
      "Stroma contains enzymes for Calvin cycle",
      "Can move within cell to optimize light capture",
    ],
    funFact: "Chloroplasts can move around inside the cell to get better light exposure!",
    foundIn: "plant",
  },
  {
    id: "chloroplast3",
    name: "Chloroplast",
    description: "Additional chloroplast",
    function: "Photosynthesis",
    size: "3-10 μm",
    color: "#16A34A",
    position: [0, 3, -0.5],
    scale: [0.85, 0.42, 0.42],
    shape: "ellipsoid",
    details: [
      "Light reactions in thylakoids",
      "Dark reactions in stroma",
      "Produces ATP and NADPH",
      "Essential for plant life",
    ],
    funFact: "Without chloroplasts, there would be no oxygen for us to breathe!",
    foundIn: "plant",
  },
  // Cell Wall (Plant only)
  {
    id: "cell-wall",
    name: "Cell Wall",
    description: "Rigid outer layer made of cellulose that provides structure",
    function: "Provides structural support and protection",
    size: "0.1-10 μm thick",
    color: "#A16207",
    position: [0, 0, 0],
    scale: [5, 5, 5],
    shape: "membrane",
    details: [
      "Made primarily of cellulose",
      "Provides rigid structure",
      "Prevents cell from bursting",
      "Has plasmodesmata for communication",
    ],
    funFact: "Wood is mostly made of plant cell walls - cellulose is the most abundant organic compound on Earth!",
    foundIn: "plant",
  },
  // Cell Membrane
  {
    id: "cell-membrane",
    name: "Cell Membrane",
    description: "Phospholipid bilayer that controls what enters and exits the cell",
    function: "Controls passage of substances in and out of cell",
    size: "7-10 nm thick",
    color: "#FBBF24",
    position: [0, 0, 0],
    scale: [4.2, 4.2, 4.2],
    shape: "membrane",
    details: [
      "Made of phospholipid bilayer",
      "Contains proteins for transport",
      "Selectively permeable",
      "Fluid mosaic model structure",
    ],
    funFact: "The cell membrane is so thin that 10,000 of them stacked would only be as thick as a sheet of paper!",
    foundIn: "both",
  },
  // Cytoplasm
  {
    id: "cytoplasm",
    name: "Cytoplasm",
    description: "Gel-like fluid filling the cell containing organelles",
    function: "Supports organelles and is site of many reactions",
    size: "Fills entire cell",
    color: "#FEF3C7",
    position: [0, 0, 0],
    scale: [4, 4, 4],
    shape: "sphere",
    details: [
      "Made of cytosol and organelles",
      "About 80% water",
      "Contains enzymes for metabolism",
      "Cytoskeleton provides structure",
    ],
    funFact: "The cytoplasm is constantly streaming and moving - it's not static at all!",
    foundIn: "both",
  },
  // Peroxisome
  {
    id: "peroxisome",
    name: "Peroxisome",
    description: "Organelle that breaks down fatty acids and detoxifies harmful substances",
    function: "Breaks down fatty acids and detoxifies peroxides",
    size: "0.1-1 μm",
    color: "#FB923C",
    position: [1.8, 1.8, 1],
    scale: [0.3, 0.3, 0.3],
    shape: "sphere",
    details: [
      "Contains oxidative enzymes",
      "Produces and breaks down H2O2",
      "Metabolizes fatty acids",
      "Abundant in liver and kidney cells",
    ],
    funFact: "Peroxisomes can replicate by dividing, similar to mitochondria!",
    foundIn: "both",
  },
  // Cytoskeleton - Microtubules
  {
    id: "microtubule1",
    name: "Microtubule",
    description: "Hollow tubes that provide structure and tracks for transport",
    function: "Provides structure, aids in cell division and transport",
    size: "25 nm diameter",
    color: "#0EA5E9",
    position: [0, 0, 2],
    scale: [0.08, 3, 0.08],
    shape: "cylinder",
    details: [
      "Made of tubulin protein",
      "Hollow tube structure",
      "Forms spindle during division",
      "Motor proteins walk along them",
    ],
    funFact: "Microtubules can grow and shrink rapidly - they are very dynamic!",
    foundIn: "both",
  },
  {
    id: "microtubule2",
    name: "Microtubule",
    description: "Part of cytoskeleton network",
    function: "Structural support and intracellular transport",
    size: "25 nm diameter",
    color: "#38BDF8",
    position: [1.5, 0, -1.5],
    scale: [0.08, 2.5, 0.08],
    shape: "cylinder",
    details: [
      "Railway for vesicles",
      "Kinesin walks toward +end",
      "Dynein walks toward -end",
      "Essential for cell shape",
    ],
    funFact: "Motor proteins can carry cargo at speeds of 1-4 μm per second!",
    foundIn: "both",
  },
  // Plasmodesmata (Plant only)
  {
    id: "plasmodesmata",
    name: "Plasmodesmata",
    description: "Channels through cell wall connecting adjacent plant cells",
    function: "Allows communication and transport between plant cells",
    size: "50-60 nm diameter",
    color: "#65A30D",
    position: [4.8, 0, 0],
    scale: [0.15, 0.15, 0.3],
    shape: "cylinder",
    details: [
      "Lined by cell membrane",
      "Contains desmotubule from ER",
      "Allows movement of molecules",
      "Creates symplastic pathway",
    ],
    funFact: "Plasmodesmata allow plants to act as one interconnected organism!",
    foundIn: "plant",
  },
]

// Get organelles for specific cell type
export function getOrganellesForCell(cellType: "animal" | "plant"): Organelle[] {
  return organelles.filter((o) => o.foundIn === "both" || o.foundIn === cellType)
}

// Color palette for labels
export const labelColors: Record<string, { bg: string; border: string; text: string }> = {
  nucleus: { bg: "rgba(139, 92, 246, 0.9)", border: "#A78BFA", text: "#FFFFFF" },
  nucleolus: { bg: "rgba(124, 58, 237, 0.9)", border: "#8B5CF6", text: "#FFFFFF" },
  mitochondria: { bg: "rgba(239, 68, 68, 0.9)", border: "#F87171", text: "#FFFFFF" },
  "rough-er": { bg: "rgba(59, 130, 246, 0.9)", border: "#60A5FA", text: "#FFFFFF" },
  "smooth-er": { bg: "rgba(96, 165, 250, 0.9)", border: "#93C5FD", text: "#FFFFFF" },
  golgi: { bg: "rgba(245, 158, 11, 0.9)", border: "#FBBF24", text: "#000000" },
  lysosome: { bg: "rgba(132, 204, 22, 0.9)", border: "#A3E635", text: "#000000" },
  ribosome: { bg: "rgba(236, 72, 153, 0.9)", border: "#F472B6", text: "#FFFFFF" },
  centriole: { bg: "rgba(6, 182, 212, 0.9)", border: "#22D3EE", text: "#000000" },
  vacuole: { bg: "rgba(167, 139, 250, 0.9)", border: "#C4B5FD", text: "#FFFFFF" },
  chloroplast: { bg: "rgba(34, 197, 94, 0.9)", border: "#4ADE80", text: "#FFFFFF" },
  "cell-wall": { bg: "rgba(161, 98, 7, 0.9)", border: "#CA8A04", text: "#FFFFFF" },
  "cell-membrane": { bg: "rgba(251, 191, 36, 0.9)", border: "#FCD34D", text: "#000000" },
  cytoplasm: { bg: "rgba(254, 243, 199, 0.9)", border: "#FEF3C7", text: "#000000" },
  peroxisome: { bg: "rgba(251, 146, 60, 0.9)", border: "#FDBA74", text: "#000000" },
  microtubule: { bg: "rgba(14, 165, 233, 0.9)", border: "#38BDF8", text: "#FFFFFF" },
  plasmodesmata: { bg: "rgba(101, 163, 13, 0.9)", border: "#84CC16", text: "#FFFFFF" },
  "central-vacuole": { bg: "rgba(196, 181, 253, 0.9)", border: "#DDD6FE", text: "#000000" },
}

export function getLabelColor(organelleId: string): { bg: string; border: string; text: string } {
  // Find base type from id
  const baseType = organelleId.replace(/[0-9]/g, "").replace(/-$/, "")
  return (
    labelColors[baseType] || labelColors[organelleId] || { bg: "rgba(100,100,100,0.9)", border: "#888", text: "#FFF" }
  )
}
